### ISSUE TITLE
Auto fill

### ISSUE THREAD

**Issue by dplim87** [Kunzisoft/KeePassDX#1466] opened 2022-12-19 14:33 UTC
Device: Pixel 4a 5g
OS: Android 13
Browser(s): Google Chrome, Brave Browser

Auto fill inconsistency on appearing for suggestions. Sometimes websites will show the auto fill prompt, other times the same websites will not. This also leads to another issue which is more of a feature request. Would it be possible to attempt reading the application for a browser domain instead of defaulting to the package name when opening Magikeyboard. I purchased the donation version of this app because it worked quite spectacularly, but lately it seems the app doesn't function properly all of them time. I don't mind workarounds but I would hope these issues might be addressed. Thank you for your hard work!

**Comment by J-Jamet** [comment] 2022-12-19 18:57
> Auto fill inconsistency on appearing for suggestions. Sometimes websites will show the auto fill prompt, other times the same websites will not.

If you're using another browser, that could be the cause, if not, it's just that your device's autofill service isn't consistent, but there's nothing I can do about it, if it shows up at least once, that means I've done my part. ;)

 > This also leads to another issue which is more of a feature request. Would it be possible to attempt reading the application for a browser domain instead of defaulting to the package name when opening Magikeyboard. 

It's already the case. You can see this issue for improvement when users make a mistake and register the applicationId of the browser instead of the domain. https://github.com/Kunzisoft/KeePassDX/issues/1465

Your issue is too vague so I close it,  there are already many open issues on the subject. https://github.com/Kunzisoft/KeePassDX/issues?q=is%3Aopen+is%3Aissue+milestone%3AAutofill

**Closed by J-Jamet** 2022-12-19 18:57 UTC
