### ISSUE TITLE
Unable to search "pr" strings v2.9.13

### ISSUE THREAD

**Issue by davidbtc2009** [Kunzisoft/KeePassDX#930] opened 2021-03-19 19:33 UTC
I have an entry in my database called "Proton Mail" normally i am able to just type the first 3 or 4 letters "pro" or "prot" for example and find an entry. However i have to type "proton " to get that entry. Other things such as "pmail", "pri" (private internet access), etc work. "Pr" does nothing, however "pt" works fine.

**Comment by J-Jamet** [comment] 2021-03-20 13:26
I can't reproduce your bug. And it's weird that it works with some letters and not others for you, there is no descrimination in the code! :D

**Comment by J-Jamet** [comment] 2021-03-20 20:29
Feel free to upload a test database so I can reproduce the problem.

**Comment by davidbtc2009** [comment] 2021-03-20 20:42
Of course it works when i created a test db. I wonder if there might be an easy way to move from one database file to a new one

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by davidbtc2009** [comment] 2021-03-20 21:04
The only major differences i see are in the encryption. My database uses keepass 2 - KDBX4.0 with Argon2d encryption where the test database uses keepass 2 - KDBX3.1 AES encryption. That shouldnt matter though.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by J-Jamet** [comment] 2021-03-24 16:29
There may be a problem in the formatting of your database. Try exporting it to XML from KeePass and re-importing it, this fixes the formatting problems.

**Comment by J-Jamet** [comment] 2021-03-30 07:10
I close this issue because is not reproducible. I advise you to export/import your database.

**Closed by J-Jamet** 2021-03-30 07:10 UTC
Labels: bug
