### ISSUE TITLE
Biometric access and organization

### ISSUE THREAD

**Issue by Gottarocket** [Kunzisoft/KeePassDX#1030] opened 2021-06-19 04:31 UTC
After new update I cant login with fingerprint it just freezes when I do so and I need to manually enter password 
Also I had organized all user password under groups which is all messed up now

**Comment by J-Jamet** [comment] 2021-06-19 08:16
Linked to #1029 

You did not fill out the bug form. I have no context so I can't deduce anything. Please fill out the bug template correctly indicating if you are using a particular file manager, what is your device, the android version and a procedure to reproduce.

**Comment by J-Jamet** [comment] 2021-06-19 08:22
> Also I had organized all user password under groups which is all messed up now

For that I do not see, I have not changed anything in the display of the groups.

Can you upload a test database that reproduces the problem?

**Comment by J-Jamet** [comment] 2021-06-21 15:59
Without new precision I close the issue because is solved in #1029.

**Closed by J-Jamet** 2021-06-21 15:59 UTC
Labels: bug, invalid
