### ISSUE TITLE
Can't open database after synchronization

### ISSUE THREAD

**Issue by Booteille** [Kunzisoft/KeePassDX#312] opened 2019-08-24 11:19 UTC
Hi! Since weeks I can not open my database through KeePass DX even if I still can open it on my desktop.

I just get the message "unable to read database".

Tell me if there is a way to provide you logs.

**Comment by J-Jamet** [comment] 2019-08-24 17:18
For logs, the easiest way is to connect the device to the PC and watch from Android Studio.

**Comment by Booteille** [comment] 2019-08-25 16:14
I am syncing the file through NextCloud. So I have the file on my own smartphone.

**Comment by Booteille** [comment] 2019-08-28 12:23
I never used Android Studio. I just installed it. How could I provide you logs?

**Comment by bastos77** [comment] 2019-09-02 21:13
Same here on 2.5.0.0.beta22 from f-droid. 
Synced with ownclod and everything went smooth in the last weeks but now from one minute to the other I can not open file neither in keePass DX nor in KeePassDroid. Only way is to open in kee.web.

**Comment by Booteille** [comment] 2019-09-10 14:34
On the desktop, I saved the database under another name, synced it through Nextcloud with my Smartphone and now I can access to it again.

**Comment by alexanderadam** [comment] 2019-10-25 07:05
Same issue here. It works though when I'm fully select the file path again via the path choosing dialogue. Otherwise it breaks everytime the file was synced.

**Comment by alexanderadam** [comment] 2019-11-14 15:49
Which third-party apps do you mean? Can you elaborate this a bit?

The bug appears when KeePassDX is directly opened without any third-party apps.

**Comment by J-Jamet** [comment] 2019-11-14 16:01
KeePass DX uses the default file manager, or is linked to the file manager that sends the open/create request (by Intent).
By default, the "File" application of the device is called. For new phones, GDrive is directly included to this in-device app.
If your phone's manufacturer has replaced this default file manager app, or if you use another third-party app (owncloud, dropbox, or other) it may not have the appropriate feature to keep the link after an event and may not handle the methods described in my previous post.
This is a strong theory that seems to be true, but I can not know without really looking into it.

**Comment by alexanderadam** [comment] 2019-11-14 16:22
Ah, I see. I'm probably using the standard File manager from Samsung (`My Files` version `10.1.04.432`) but I strongly doubt that they will listen to me if I write them that everything works flawlessly _except_ KeePassDX. :wink:

**Comment by J-Jamet** [comment] 2019-11-14 16:33
I understand, that's why I planned to make another application File Manager (with plugins for network connections) that can handle this kind of case, but I must already finish KeePass DX.
I recommend downloading another compatible file manager under free license. (I do not know yet which ones are)
Other apps bypass this problem by integrating all synchronization methods and integrating all third-party APIs but  it's dangerous in my opinion and goes against the principle of encapsulation of components.

**Comment by alexanderadam** [comment] 2019-11-14 16:40
Another small question: why appeared this problem so suddenly? Everything was totally fine until an update from August (?).
Was it a necessary refactoring or something similar?

**Comment by J-Jamet** [comment] 2019-11-14 20:03
In previous versions of the app, the problem was also present but less noticeable if the database was created with the app.
Before, the code included a big deprecated file creation library (which does the job of a file manager) but only for creation. The application knew the direct link of the file created (file: // ..) the first time.
If the file is reopen later, the problem was present. As the library was not very well done, I harmonized the methods that use the intent content provider and remove the deprecated lib.
Direct links are not real solutions because requires to redo a complete file manager in the app.

**Comment by alexanderadam** [comment] 2019-12-20 10:31
Did you change something regarding this in November or December?
Because I cannot reproduce this bug anymore.

**Comment by J-Jamet** [comment] 2019-12-20 11:59
@alexanderadam Yes I changed several things, that's why there are updates, after I haven't tested the remote databases yet. I resolve errors as I go along. Yes it is related to # 192, the content provider of the File Manager application used is often the cause.

**Comment by alexanderadam** [comment] 2020-02-13 13:37
I just had to get a password an used the autocomplete thing to open KeePassDX.
But as usuall I ran into this issue here, because I didn't reset the path after the sync.

I wasn't able to reset the path, though because using the 'back arrow' in KeePassDX returns back to the other app. So I guess you could at least check whether the 'stored' path is still existing _before_ the user clicks the `Open` button, right?
This way it should at least be possible to go to the path selection dialogue first.

Or do I miss something?

**Comment by J-Jamet** [comment] 2020-03-07 13:59
If you return to the other app when you click on the back arrow, it means that you have not opened your .kdbx file from the "Open" button in KeePassDX. In this case, the link may be broken because the other app revokes access to the saved link. I visually resolved the problem with version 2.5beta27 by hiding broken links. Just reopen the file from the other app or use the "Open" button.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

**Comment by J-Jamet** [comment] 2020-03-26 13:42
Rereading the conversation, it appears that the issues are mixing and that several problems have already been resolved. I therefore close this issue, if you still have special problems, you can open a new issue by filling out the bug form.

**Closed by J-Jamet** 2020-03-26 13:42 UTC
Labels: bug

**Comment by alexanderadam** [comment] 2020-03-26 16:34
@Booteille and @bastos77, may I ask on which devices you had those issues?

**Comment by bastos77** [comment] 2020-03-26 16:39
Device of the screenshot is Android Lenovo Tab 4 8.

**Comment by Booteille** [comment] 2020-03-27 07:16
> @Booteille and @bastos77, may I ask on which devices you had those issues?

One Plus One 3T and LineageOS 16 Nightly (Or maybe I was still on the version 15 the last summer... can't remember.)
