### ISSUE TITLE
Emoji in notes are deleted

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#796] opened 2020-11-23 08:54 UTC
(From Steven)
I had a note in my vault with emoji in it, but they are erased when I open it in this app.

**Comment by Ilithy** [comment] 2020-11-23 10:13
Hi;
I can confirm the bug,
tested by adding emoji in the notes,
after saving the changes, closing the database and reopening it,
the emoji present in the notes disappeared (they are not converted, just deleted).
Thanks

**Comment by JahidFariz** [comment] 2020-11-26 21:06
Some of emojis are not deleted. Not all emojis are deleted except like "☺☹☠❣❤✋✌☝✊✍⛷⛹☘☕⛰⛪⛩⛲⛺♨⛽⚓⛵⛴✈⌛⏳⌚⏰⏱⏲☀⭐☁⛅⛈☂☔⛱⚡❄☃⛄☄✨⚽⚾⛳⛸♠♥♦♣♟⛑☎⌨✉✏✒✂⛏⚒⚔⚙⚖⛓⚗⚰⚱♿⚠⛔☢☣⬆↗➡↘⬇↙⬅↖↕↔↩↪⤴⤵⚛✡☸☯✝☦☪☮♈♉♊♋♌♍♎♏♐♑♒♓⛎▶⏩⏭⏯◀⏪⏮⏫⏬⏸⏹⏺⏏♀♂⚧✖➕➖➗♾‼⁉⚕♻⚜⭕✅☑✔❌❎➰➿〽✳✴❇©®™ℹⓂ㊗㊙⚫⚪⬛⬜◼◻◾◽▪▫". These emojis are not deleted

**Comment by hokonch** [comment] 2020-11-28 12:30
> These emojis are not deleted

Not surprising because they are 2-byte or 3-byte characters.
In fact, KeePassDX cannot save non-emoji characters such as 𠮟 (Scold), which is the only 4-byte kanji (Chinese characters) that appears in commonly used Japanese.

**Closed** 2021-02-15 11:55 UTC
Labels: bug, completed developments
