### ISSUE TITLE
Unable to copy password to clipboard on Google Pixel 3a

### ISSUE THREAD

**Issue by coilheadfred** [Kunzisoft/KeePassDX#328] opened 2019-09-09 07:51 UTC
Every time I try to copy a password it won't do anything. Did not have this issue on a different device.

**Comment by J-Jamet** [comment] 2019-09-10 09:51
This bug will be very difficult to solve because I do not have a Google Pixel 3, can you tell me if there is a custom clipboard on your device?

**Comment by J-Jamet** [comment] 2019-09-10 13:57
You are sure not to have unchecked the setting "App Settings -> Clipboard Trust" ?

**Comment by coilheadfred** [comment] 2019-09-10 19:31
Yes I am sure. It's turned on. I am not sure why it isn't working. My other keepass app works

**Comment by flocke** [comment] 2019-09-11 04:38
I just tried on my Pixel 3a to see if I can maybe get a logcat or debug further, big it seems to work for me. I copied and pasted a few passwords and it worked without problems for all of them.

**Comment by coilheadfred** [comment] 2019-09-11 14:49
Maybe I'll uninstall and install again.

**Comment by J-Jamet** [comment] 2019-11-12 12:14
This bug is very specific and not reproducible, I close the issue.

**Closed by J-Jamet** 2019-11-12 12:14 UTC
Labels: bug
