### ISSUE TITLE
Login screen has to be completed multiple times

### ISSUE THREAD

**Issue by KaaCee** [Kunzisoft/KeePassDX#593] opened 2020-06-17 19:50 UTC
**Describe the bug**
Login screen has to be completed multiple times.

**To Reproduce**
1. Open KeePassDX and go to the login screen of your database
2. Enter your password and click on "open"
3. If you get into your database: leave KeePassDX by clicking on the back button until you get to your home screen. Then, start over with step 1
4. Sometimes you get onto the login screen, sometimes onto the DB selection screen and sometimes KeePassDX closes with error "KeePassDX has been closed multiple times"

**Expected behavior**
You should always reach the database content in step 3

** Keepass Database **
 - Created with: KeePassDX
 - Version: 2.6
 - Location: local directory
 - Size: 1.29kb
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.6
 - Build: libre
 - Language: german

**Android (please complete the following information):**
 - Device: Motorola Moto G7
 - Version: 10 / LineageOS 17.1

**Additional context**
Can be reproduced with fresh install of KeePassDX and completely new database, also generated with KeePassDX.

**Comment by J-Jamet** [comment] 2020-06-18 07:34
Indeed, there is a bug in the workflow which makes the application stop. This is due to the onResume() function which is not called by the parent activity. The problem will be fixed in the next version.

**Comment by J-Jamet** [comment] 2020-06-18 13:09
The problem is solved in version 2.7

**Closed** 2020-06-18 13:08 UTC
Labels: bug, completed developments
