### ISSUE TITLE
[2.9.14_beta] Opening a database is slow

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#923] opened 2021-03-12 08:03 UTC
**Describe the bug**
With the 2.9.14 update, opening a database takes more than 30 seconds for some users.

**Expected behavior**
Opening as fast as in version 2.9.13

I don't have much information about this bug, if you have it while testing the beta, please indicate your database version, android version and indicate the approximate number of entries you have with the number of binaries.

The first thing is to identify the problem, it is possible that this comes from a non-optimized read loop or the new NDK but I can't reproduce the problem yet.

Edit: The problem is reproducible but it is necessary to know where exactly the slowdowns come from.

~Edit: It is also possible that the problem is simply a bad compilation. For the moment, users have reported the problem only on the Pro Beta version, but not on the Free Beta version. Please let a message if you also have the problem on the Free Beta version.~

~I just noticed that all the users who report the problem have a Samsung Galaxy 10 (Note10, S10, etc ...)~

**Comment by J-Jamet** [comment] 2021-03-12 12:49
I've done a lot of testing and I think I've found the issue and you won't believe it: **the problem comes from the upgrade of the Android Material library from version 1.1.0 to 1.3.0.** Commit: 6357a30acbbc89d5df8b6a3aa5206452bc09fff6
I have no idea why an official graphics library causes these slowdowns.

I will downgrade the library and make a new version 2.9.15 of KeePassDX.

**Comment by bama35453** [comment] 2021-03-12 14:28
I just received the latest Update and the issue still persists. 
I am using a Galaxy Note 10+ with Stock Android 11. Opening a database takes approximately 30 secs.
On my Galaxy Tab S7 (also stock Android 11) the database opens a bit quicker. On that device it takes between 10 and 15 secs to open the database.
Could this behavior be linked to using a key file?

**Comment by J-Jamet** [comment] 2021-03-12 14:38
At the moment I don't understand what changes these behaviors, and I can't debug it as a crash because there is no error. On my devices it was the library update, which I changed in the new beta.
I haven't changed anything about the key files, so I don't think so.

**Comment by J-Jamet** [comment] 2021-03-12 14:58
Some users think that the problem only affects V4 databases, I will look into this.

**Comment by J-Jamet** [comment] 2021-03-12 16:23
Since my first fix for version 2.9.14, I can't reproduce any slowdown when opening. Changing a v4 database to v3.1 and vice versa does not change anything for me. I really don't understand where the problem comes from.

**Comment by Bob-465** [comment] 2021-03-12 17:27
Also in version 2.9.14 the opening of the database takes about 3-4 seconds (Android 11, Galaxy S10+). Database with key file. The same database opens immediately on Android 9 (Zenfone3).

**Comment by J-Jamet** [comment] 2021-03-12 17:37
The users who report the problem all have Samsung. But I don't have any to test, which is problematic.

**Comment by J-Jamet** [comment] 2021-03-12 17:48
Feel free to upload test databases indicating the unlock time and the associated device.

**Comment by Bob-465** [comment] 2021-03-12 18:38
Sample database test.kdbx - Password=test
Loading the database:
Galaxy S10+ = 4.8 seconds
ASUS Zenfone 3 = 0.8 seconds
[test.zip](https://github.com/Kunzisoft/KeePassDX/files/6132225/test.zip)

**Comment by arkhillneo** [comment] 2021-03-12 23:53
Hi
I found if file size of the database bigger then 13kb or more , the loading time issue starting to be observed on Samsung devices.
But still, it only happens on Samsung devices with 2.9.14.

I made the sample file from Desktop PC version KeePass Password Safe by copy&past items(https://keepass.info/).
So I am wondering the loading issue is not depends on the file, but on the phone device with 2.9.14.

I also roll-back to 2.9.13 by installing the apk form F-Droid. 2.9.13 works just fine on the same Samsung devices with the same database file.

Sample database t01_eng.kdbx - Password=12345 , file size 64kb.
Loading the database with 2.9.14:
Galaxy Tab S7+(Android11) = about 8 seconds
Galasy Note10+(Android11) = about 8 seconds
HTC U11(Android9)  = about 0.8 seconds
Loading the database with 2.9.13:
Galaxy Tab S7+(Android11) = about 0.8 seconds
[t01_eng.zip](https://github.com/Kunzisoft/KeePassDX/files/6133498/t01_eng.zip)

**Comment by M0nty-Pyth0n** [comment] 2021-03-13 00:37
I have the same phone Note 10+ phone/android version 11 and observe the
same delay when opening. I too have a key file but did not notice this
delay before in prior versions.

On Friday, March 12, 2021, bama35453 ***@***.***> wrote:
> I just received the latest Update and the issue still persists.
> I am using a Galaxy Note 10+ with Stock Android 11. Opening a database
takes approximately 30 secs.
> On my Galaxy Tab S7 (also stock Android 11) the database opens a bit
quicker. On that device it takes between 10 and 15 secs to open the
database.

**Comment by J-Jamet** [comment] 2021-03-13 09:28
Thanks for the feedbacks! :)
I still can't reproduce the problem so I'll have to make some blind modifications. :(

_Also note, many people are confused to see updates on Play Store Beta with the same version number 2.9.14.
This is normal, as the TAG is not yet created, the version is still being modified, only the version code is updated (58->59). This corresponds to the https://github.com/Kunzisoft/KeePassDX/tree/release/2.9.14 branch, don't be confused by the term "release" of the branch either, it's just git flow that is used and it's more convenient to do merge and tag. Once the problem is fixed, the branch will be merged, the tag created and the release packaged and F-Droid can build the version. I would like to remind some users that the beta is made for testing ;)_

**Comment by J-Jamet** [comment] 2021-03-13 09:53
For those who want the upload history on the Play Store : 
[KeePassDX-2.9.14_beta01.zip](https://github.com/Kunzisoft/KeePassDX/files/6134466/KeePassDX-2.9.14_beta01.zip) : First
[KeePassDX-2.9.14_beta_02.zip](https://github.com/Kunzisoft/KeePassDX/files/6134469/KeePassDX-2.9.14_beta_02.zip) : Downgrade Material lib 1.3.0 to 1.1.0 **(Current Play Store Beta Version)**

Thanks again for your test databases, it allowed me to make some conclusions, the slowdown problem:

- is not related to the binaries
- is not related to custom icons
- seems to happen only on Samsung devices with KeePassDX-2.9.14_beta02 but on many devices with KeePassDX-2.9.14_beta01

In version 2.9.13, the Material lib version 1.0.0 was used, so I will downgrade the library again, there is a chance that the transition from version 1.0.0 to 1.1.0 of the library will also cause problems. The problem is that I have to change a lot of code for this downgrade. I will try this method and come back to you.

**Comment by J-Jamet** [comment] 2021-03-13 10:50
[KeePassDX-2.9.14_beta_03.zip](https://github.com/Kunzisoft/KeePassDX/files/6134595/KeePassDX-2.9.14_beta_03.zip) (only for testing, is not stable and not in real beta)

OK, Here is an apk to validate or not the theory of the Material library. Beware, the development is not finished, so the custom icons are not usable anymore (because it used the updates of the library of course). But if you can tell me if it solves the problem of slowness, at least I will know if it's a good theory.

**Comment by Bob-465** [comment] 2021-03-13 11:20
Tested on Galaxy S10+
Sorry, no improvement in the speed when opening the database

**Comment by J-Jamet** [comment] 2021-03-13 11:23
OK, I'll try to make some more blind performance improvements.

**Comment by arkhillneo** [comment] 2021-03-13 11:27
Tested on Galaxy Tab S7+
Issue still persists.

**Comment by J-Jamet** [comment] 2021-03-13 12:45
I think I know what the problem is : before doing optimizations I allocate empty memory directly to each icon (empty custom for each icon) when they are decrypted from the database. By allocating memory only when needed, it should be more efficient. I think some systems do optimization by themselves at runtime, others don't.
Can you test this new compilation?

[KeePassDX-2.9.14_beta_04.zip](https://github.com/Kunzisoft/KeePassDX/files/6134777/KeePassDX-2.9.14_beta_04.zip)

Thank you :)

**Comment by arkhillneo** [comment] 2021-03-13 12:56
Tested beta_04 on Galaxy Tab S7+
I can confirm the Issue is fixed!

**Comment by J-Jamet** [comment] 2021-03-13 12:58
Great, thanks a lot for your feedback, it's really a great help. I'll finalize some optimizations and upload this new beta version on the store! :)

**Comment by arkhillneo** [comment] 2021-03-13 14:15
Just received the new version from store.
Loading issue fixed on all my Samsung devices, Thanks a lot.

**Closed** 2021-03-13 14:15 UTC
Labels: bug, completed developments
