### ISSUE TITLE
No Wirte acces on Android 10

### ISSUE THREAD

**Issue by kiam001** [Kunzisoft/KeePassDX#484] opened 2020-03-09 19:43 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

** Keepass Database **
 - Created with: [e.g Windows KeePass 2.42]
 - Version: [e.g. 2]
 - Location: [e.g. Remote file retrieved with GDrive app]
 - Size: [e.g. 150Mo]
 - Contains attachment: [e.g. Yes]

**KeePassDX (please complete the following information):**
 - Version: [e.g. 2.5.0.0beta23]
 - Build: [e.g. Free]
 - Language: [e.g. French]

**Android (please complete the following information):**
 - Device: [e.g. GalaxyS8]
 - Version: [e.g. 8.1]

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment] 2020-03-09 19:45
Duplicate of #480

**Closed** 2020-03-09 19:46 UTC
Labels: bug, duplicate
