### ISSUE TITLE
Add entry in kdb (v1) empties the file

### ISSUE THREAD

**Issue by pixel2user** [Kunzisoft/KeePassDX#1201] opened 2022-01-18 02:31 UTC
**Describe the bug**
All of a sudden my db size was 0 Byte! :-(

**To Reproduce**
1. Open website and select username field
2. Select autofill pop-up

**Expected behavior**
DB is not corrupted, but instead it's content is loaded.

**KeePass Database**
 - Created with: KeePassDX 3.0.x
 - Version: 2
 - Location: local
 - File provider (`content://` URI): content://com.android.externalstorage.documents/document/primary:KeePass/keepass.kdb
 - Size: 0 kb (after bug corrupted the db!)
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: 2.0.4
 - Build: F-Droid
 - Language: German

**Android (please complete the following information):**
 - Device: Google Pixel 2
 - Version: 10 (LineageOS)

**Additional context**
 - Browser for Autofill: Brave, newest version

**Comment by J-Jamet** [comment] 2022-01-18 08:24
I just saw the bug for old version 1 databases (kdb) created with a windows version of Keepass 1.
You indicate in the description a version 2, can you confirm that you have a version 1?

I checked and the code in development solves the problem, but I have to deploy version 3.1 faster than planned. It happened because the architecture of this format is very very little permissive with a list that goes in tree when saving, and there is a problem because the root does not allow to save with a virtual entry root.

I strongly recommend migrating to the kdbx versions which can be tested more easily. While waiting for the upgrade, do not modify your kdb file.

(I even think that with Dominik, I'm the only one to maintain this format, all the other KeePass clients boycott it. :D)

**Comment by J-Jamet** [comment] 2022-01-18 11:55
Fixed in version 3.1 : https://github.com/Kunzisoft/KeePassDX/releases/tag/3.1.0

**Closed** 2022-01-18 11:54 UTC
Labels: bug, completed developments

**Comment by pixel2user** [comment] 2022-01-18 12:12
@J-Jamet "the code in development solves the problem, but I have to deploy version 3.1 faster than planned."

Do you know which version of KeePassDX introduced this bug? These versions should be taken down from F-Droid. I updated to KeePassDX 3.0.4 on 1/1/2022. I'm not sure which version I used before that, but I didn't had any problem before.

Thank you for the fast fix. Too bad this won't bring my lost entries back, since I didn't backup my db (internal memory only) for too long! :-( This will be a lesson for me for sure...

**Comment by J-Jamet** [comment] 2022-01-18 12:45
Sorry for that. Honestly, I don't know, it must be when the virtual group management code was harmonized at the root level of the tree.
When exactly the bug was introduced : I would say between version 3.0.0 and 3.0.4 but I'm not even sure.
It's a technical bug in the version 1 parser (parser inherited from keepassdroid) that I greatly improved before coding the data merge system #840, so I solved it without knowing it, that's why I was able to deploy the new version quickly.

I recommend you to download the version from this [github repo](https://github.com/Kunzisoft/KeePassDX/releases/tag/3.1.0) until the F-Droid version is available. If it's a bug that's been there for a long time, I haven't seen it at all and neither have the users before you apparently because I didn't get any feedback on this specific problem before your issue. I think very few users are using version 1 database and it is also necessary to create an entry type in a group at level 1 of the tree to reproduce the bug. Since I work on Linux and KeePass version 1 is not compatible with my system, I mainly test kdbx databases from version 3 (It is also the minimum database versions of all new databases since the creation of KeePassDX.).

So I can recommend you also to migrate to kdbx even if the code is fixed in the new version.
