### ISSUE TITLE
Not auto filling username

### ISSUE THREAD

**Issue by leowankerddd** [Kunzisoft/KeePassDX#1804] opened 2024-04-07 18:32 UTC
Auto fill only kicks in after I type in the username myself. If I have the option to tap on the password it fills in the password but not the user ID.

I switched from keypass2Android and it works for filling in the user ID and the password. When I get to a login page and tap the user ID autofill pops up with keypass2 Android when I use DX software it only pops up on the password which is useless if I don't know what the ID is.

**To Reproduce**
Set DX as autofill provider and try and log into an app or a website and you never get prompted for autofill on the user ID.

1. Go to app or web login screen. 
2. Click on 'username'
3. Nothing happens 
4. Need to switch to DX to retrieve the user ID.

**Expected behavior**

I expect when prompted for username and I tap the username field for keypass DX to offer to fill in the username. When I tap on username nothing happens. When I tap on my password it pops up with DX. 

Keepass2Android functions as it's supposed to. It auto fills both the user ID and the password.

**KeePass Database**

 - Created with: keepassxc on Windows. 
 - Version: 2.77
 - Location: Remote file retrieved with GDrive app

 - Size: 2mb
 - Contains attachment: no

**KeePassDX:**

 - Version: [4.0.5]
 - Build: [Free]
 - Language: [english]

**Android:**

 - Device: [GalaxyS21]
 - Version:

**Additional context**

 - Browser for Autofill: [e.g. Chrome version X]

**Comment by auanasgheps** [comment] 2024-04-11 17:38
I can confirm I'm seeing this as well. It's a recent issue,  I can't remember since it started.
It used to fill the username.

**Comment by shortwavesurfer2009** [comment] 2024-04-13 12:04
I am having this same problem and it has been going on for quite a long time. I actually came here to create a new issue for this exact thing, but ran across this one first.

**Comment by g-wagen** [comment] 2024-04-13 13:50
Just signed in to confirm this issue as well. Also to confirm the current behavior described by @leowankerddd . 
It used to autofill both username and the password but since recently this behavior stopped.

Android 14
KeePassDX 4.0.5
Brave 1.64.116, Chromium 123.0.6312.105

**Comment by J-Jamet** [comment] 2024-04-14 16:58
I link this issue to https://github.com/Kunzisoft/KeePassDX/issues/1665 and close it for duplicate.
(Just tested with Android 14, chrome 113.0.5672.136, github.com/login and it works fine, we continue the discussion in #1665)

**Closed by J-Jamet** 2024-04-14 16:58 UTC
Labels: bug
