### ISSUE TITLE
Saving a KDBX 4.0 database prevents it from being read on the PC side

### ISSUE THREAD

**Issue by succeedmr123** [Kunzisoft/KeePassDX#966] opened 2021-04-23 10:58 UTC
**Describe the bug**
A database crated on PC side and loaded, manipulated and saved again in Android KeepassDX produces a database that faols to load, and throws
an error  on PC side KeepassXC, with an error;

"Error while reading the database: XML error:
Premature end of document.
Line 2830, column 46989"

Meanwhile, on the Android side, same database appears as error-free - no KeepassDX complaints.

Therefore, looks like decrypt is ok  at least, and there is either;
-de|compress error
-incompatibility regression on XML parsing, and based on an error type, possible truncation/corruption

(can not error check with another read-only db from KeepassDX Android to confirm the exact issue).

**To Reproduce**
1. Go to KeepassDX..load the database, save some entries on your Android device
2. Reload the database in PC KeepassXC. the abovementioned error appears

**Expected behavior**

Keepass KDBX database corruption-free (both decrypt or XML parsing) -  compliant behaviour for error-free operation in other Keepass apps.

Additional expectation stemming from incompatibility regression is to undo the incompatibility and check for possible data corruption

**KeePass Database**
 - Created with: Windows KeePassXC 2.6.4
 - Version: Keepass 2 - KDBX 4.0 , db compression enabled as well (KeepassDX Android side refers as GZIP compression)
 - Location: Remote file retrieved with app RaiDrive 2020.6.80 (Multi-cloud, multi-account sync app)
 - Size: cca 1,89 Mo
 - Contains attachment: methinks no..(favicons or what?)

**KeePassDX (please complete the following information):**
 - Version: 2.9.17
 - Build: Libre, from Play store
 - Language: En

**Android (please complete the following information):**
 - Device:  Samsung Galaxy Note9
 - Version: 10

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment] 2021-04-23 11:26
It seems this problem does not come from KeePassDX but from your file manager app that performs the synchronization between devices.
Here it seems that the end of your file has not been transferred correctly.
If you think the problem is really with KeePassDX, please upload a test .kdbx file to reproduce the problem locally.

**Comment by succeedmr123** [comment] 2021-04-25 17:00
Thanks a lot @J-Jamet  , I do appreciate a helpful and concise answer, and oblige to do the required testing to pinpoint the exact cause.

**Comment by J-Jamet** [comment] 2021-06-12 08:28
No further information, I close the issue

**Closed by J-Jamet** 2021-06-12 08:28 UTC
Labels: bug
