### ISSUE TITLE
Compressed databases get corrupted when saved

### ISSUE THREAD

**Issue by trymeouteh** [Kunzisoft/KeePassDX#432] opened 2020-01-17 20:19 UTC
**Describe the bug**
With compressed database files, after the database is modified in KeePassDX, it will no longer be readable in KeePassXC. A temporally solution for now is to save the database uncompressed

**To Reproduce**
1. Create a database in KeePassXC and have some data in the database (over 50kb in compressed size)
2. Open the database in KeePassDX and edit and field and save the database
3. Try opening the database in KeePassXC, it will give the error "Error while reading the database: Unable to decompress binary" but the database can still be opened in KeePassDX

https://github.com/keepassxreboot/keepassxc/issues/4050

**Comment by J-Jamet** [comment] 2020-01-18 09:29
Duplicate of https://github.com/Kunzisoft/KeePassDX/issues/412. Will be fixed in the next version.

**Closed** 2020-02-10 22:14 UTC
Labels: bug, completed developments, duplicate
