### ISSUE TITLE
Manual Selection does not fill out form

### ISSUE THREAD

**Issue by trymeouteh** [Kunzisoft/KeePassDX#1735] opened 2024-01-11 21:30 UTC
**Describe the bug**

When the "Manual Selection" setting is enabled in thr autofill settings, when using a keyboard to fill out a form to login to an account, it will not fill out the form (username, password)

**To Reproduce**

1. Have Manual Selection enabled
2. Click on a login username field on a website (I used amazon.com)
3. Unlock KeePass database
4. Select the entry (In ny case amazon.com)
5. Nothing happns

**Expected behavior**

My email/usernane should be pasted in the form

**KeePass Database**

 - Created with: KeePassDX
 - Version: 2
 - Location: Local Device
 - Size: 20kb
 - Contains attachment: No

**KeePassDX:**

 - Version: [e.g. 2.5.0.0beta23]
 - Build: 4.0.5
 - Language: English

**Android:**

 - Galaxy Tab S5e
 - Android 13

**Additional context**

 - Fennec (browser)
 - amazon.com (Website to log into)

**Comment by J-Jamet** [comment] 2024-04-14 17:17
Amazon is on two screens. Duplicate of https://github.com/Kunzisoft/KeePassDX/issues/1272

**Closed by J-Jamet** 2024-04-14 17:17 UTC
Labels: bug
