### ISSUE TITLE
"Invisible" entries

### ISSUE THREAD

**Issue by droopy4096** [Kunzisoft/KeePassDX#401] opened 2019-12-01 07:18 UTC
Today while adding an entry to a sub-folder in KeePassDX I came across a strange issue: entry was created as expected, but the only way I can navigate to it is via search bar. Worse yet - any subsequent entries suffer the same fate: while you can't find them browsing db, you can search for them. 

In the past I came across similar issue where app was mis-filing entries in wrong folders. 

It would be useful to enhance UI to allow:
* to see full path to entry
* initiate move of an entry to a different folder from within entry view (or edit) screen.

**Comment by J-Jamet** [comment] 2019-12-01 08:55
Can you tell me the version of KeePass DX used, in which sort mode are you when the problem is present and the version of your database? Do the entries reappear after closing and reopening the database?
I think the problem comes from UUID but I have already solved the problem and I can not reproduce it so I do not see where it comes from.

**Comment by droopy4096** [comment] 2019-12-01 15:14
it was b22, sorted by name. entries do not appear after closing db/app. 

I tried b25 which announced that there we duplicate id's, but after it "fixed" them b22 can't open database due to corrupt base64 encoding, while b25 is showing most entries in duplicates *and* still not showing entries in question

**Comment by J-Jamet** [comment] 2019-12-01 15:27
Okay, I understand.
The beta25 corrects a lot of problem for database with bad formatting. If you have multiple entries with the same name then KeePassDX has detected several entries with the same UUID and does not know which one is good.
It generates a new entry with a new UUID to not lose information, it is up to you to clean manually generated entries.
I recommend that you open your database with KeePass2, export your database in XML, and re-import it to get the correct formatting. Without this, you may not be able to open your database if it save.
You should also keep KeePassDX up to date to take advantage of the latest patches.

**Closed** 2019-12-05 18:21 UTC
Labels: question
