### ISSUE TITLE
OTP setup scan QR code

### ISSUE THREAD

**Issue by Fehertukor** [Kunzisoft/KeePassDX#743] opened 2020-10-06 17:36 UTC
I love your app and thank you for it!

Issue:
I trie to setup everyone of my accounts with 2FA.
and it works nicely but I have a ton of accounts.
(and the codes are really long)

Solution:
Would it be possible to scan the QR codes what needed to setup 2FA? Can you help us with this?

alternative:
An other third-party app, but I would like to keep in Keepass.

thanks!

**Comment by J-Jamet** [comment] 2020-10-07 08:28
Duplicate of #556

**Closed by J-Jamet** 2020-10-07 08:28 UTC
Labels: feature
