### ISSUE TITLE
Database locks after clipboard timeout 

### ISSUE THREAD

**Issue by MichiFr** [Kunzisoft/KeePassDX#974] opened 2021-04-29 19:04 UTC
**Describe the bug**
The database itself locks after the clipboard timeout expires. The setting for this to happen is however deactivated! 

**To Reproduce**
1. Open database 
2. Select any account 
3. Watch the Android notifications on top for the timeout bar decreasing from max to zero
4. When the bar reaches the left side, the timeout is reached and in the background the database automatically closes. 

**Expected behavior**
The appropriate setting for any clipboard timeout is off as well are any other settings. So there is IMO not need for closing the database nor do I want this to happen 

**KeePass Database**
 - Created with: Windows KeePass latest version 2.

**KeePassDX (please complete the following information):**
 - Version: 2.9.20
 - Language: DE

**Android (please complete the following information):**
 - Device: Huawei Tab
 - Version: 9

Maybe I've overlooked sthg, but I've checked every option and deactivated anything related to any timeout to no avail.

**Comment by J-Jamet** [comment] 2021-04-29 19:46
I just tested it and I can't reproduce this behavior. 
`Settings - Form filling - Clear` at closing does not close the application when disabled and vice versa.

But I discovered another bug when the time is 0, which I just fixed.

**Comment by J-Jamet** [comment] 2021-04-29 19:56
I think you had tested with an already open notification. The settings only took effect when a new notification was opened. I just improved this behavior so that the user is less lost.

**Closed** 2021-04-30 09:35 UTC
Labels: bug, completed developments

**Comment by MichiFr** [comment] 2021-04-30 14:47
Hm, definitely does close the database. 

Maybe this is related to the Magikeyboard? Because after jumping into the details of any account, the timeout bar in the notifications shows as information "[accountname] is available via Magickeyboard" and the timeout bar decreases from the right to the left side. When it reaches the left side, the database closes. 

BTW, can I switch the language of the app to English as this would ease the communication here?

**Comment by J-Jamet** [comment] 2021-04-30 15:08
This is not the same functionality so it's not the same setting ;)

> BTW, can I switch the language of the app to English as this would ease the communication here?

The application follows the language of the device, so you just have to set your device to English.
