### ISSUE TITLE
Folder renaming changes the parent folder

### ISSUE THREAD

**Issue by panthora** [Kunzisoft/KeePassDX#1239] opened 2022-02-14 21:05 UTC
When renaming a folder, the parent folder gets the new name. The folder to be changed keeps its old name.

**Comment by panthora** [comment] 2022-02-14 21:30
Renaming by longpressing a folder in the list leads to the bad behavior. Renaming by longpressing the last breadcrumb from the headline works as expected.

**Comment by J-Jamet** [comment] 2022-02-14 22:00
Please fill the template correctly. I can't guess the version number of the application, or your device, or the database version. Also indicate a clear and reproducible procedure for the issue.

**Comment by J-Jamet** [comment] 2022-02-14 22:49
Reproducible in 3.3.0_beta02

**Comment by panthora** [comment] 2022-02-15 10:49
Here are more details:

KeePassDX Version: 3.3.0_beta01
DB-Version: V2 - KDB3.1
Device: Pixel 6 Pro
Android: 12, Build:  SQ1D.220205.003

Procedure:
- Open Database
- Longpress on a group/folder
- Open the three-dot-menu (bottom right)
- Choose Edit
- Change Name or icon
- Press OK

=> The name and icon will be applied to the parent group/folder (or root group when this is parent). The group/folder that should be edited will stay untouched.

**Comment by J-Jamet** [comment] 2022-02-15 10:54
Thank you, it's clearer and it saves time in resolving anomalies.
Here I was afraid that the problem was in production, so I tested the current stable version first without finding the problem before I realized that it was an issue with the new beta. :D

I'll fix some other bugs and make a 3.3.0_beta02 release within the week.

**Comment by panthora** [comment] 2022-02-15 11:45
Thanks for the quick reply and the quick fix.
I just hadn't thought that this info is important of course - I was still upset about the mess in my database ;-)

Here is a walkaround for those who want to change group/folder names or icons before the fix is online:

- Navigate inside the group you want to change
- Longpress on the group-name from the navigation bar (top)
- Do your changes

**Closed** 2022-02-16 14:37 UTC
Labels: bug, completed developments
