### ISSUE TITLE
Improve the interface of recently opened databases displayed

### ISSUE THREAD

**Issue by ghRegEdit** [Kunzisoft/KeePassDX#469] opened 2020-02-20 16:37 UTC
I would like to suggest including some features in future releases:

~1. Download and select a custom icon for a record or group.
1.1 Download "favicon" by URL.
2. Download attachments.
3. Works with cloud services (gdrive: //, etc., if possible) Now it works with a remote file, but using the https: // protocol)~
4. Improve the interface of recently opened databases displayed. (Add the ability to enter a manual path to the database - In case of opening via a shared link)

**Comment by J-Jamet** [comment] 2020-02-22 09:39
1. Duplicate of #96 
2. You can already download attachments but not yet upload in database -> Duplicate of #189 
3. Explanation in wiki : https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync -> Issues in https://github.com/Kunzisoft/KeePassDX/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Database+Sync%22
4. The purpose is to only use content providers of file managers. In my opinion there is no point in entering a URI manually. We just have to recover the intent of a shared file. If there is one, can you tell me a concrete workflow.

(Next time, please look at the open issues and open one issue by request, thank you)

**Comment by J-Jamet** [comment] 2020-03-28 12:37
No answer on a concrete workflow. Cloud file managers will be updated in the wiki to indicate the level of compatibility.

**Closed by J-Jamet** 2020-03-28 12:37 UTC
Labels: feature
