### ISSUE TITLE
Chromebook: Black screen 

### ISSUE THREAD

**Issue by fliby57** [Kunzisoft/KeePassDX#252] opened 2019-04-26 17:40 UTC
Hi,
Navigation is fine in the application till click on "EDIT" , then the screen is black (see attached picture)
Could you please investigate.
Many thanks,
Fred

![Snip-it_1556300142066](https://user-images.githubusercontent.com/50027803/56825851-09774680-688d-11e9-83ea-c76e54f92261.jpg)

**Comment by J-Jamet** [comment] 2019-04-27 11:44
Thank you for the feedback, I have not yet managed the chromebook, I will try to install an emulator to increase compatibility.

**Comment by J-Jamet** [comment] 2019-07-29 15:50
I have tested and I have no problem with the Chromebook emulator, can you provide me the logs?

**Comment by J-Jamet** [comment] 2019-08-17 14:43
Without feedback and unable to reproduce the anomaly, I close the ticket. (Maybe fixed with the new versions).

**Closed by J-Jamet** 2019-08-17 14:43 UTC
Labels: bug
