### ISSUE TITLE
Saving database file from NextCloud crashes the app

### ISSUE THREAD

**Issue by func0der** [Kunzisoft/KeePassDX#16] opened 2017-12-22 19:59 UTC
How to reproduce:
----
1. Install NextCloud
2. Put a database file in your cloud
3. Open KeePassDX and open the file from the file chooser
4. Try to create an entry (name is enough)
5. Save
-> The app crashes

Android: Marshmallow 5.0

Tell me, what you need more, I'll try to deliver.

**Comment by J-Jamet** [comment] 2017-12-22 20:11
Thanks for your reply, I'll investigate and try to solve the problem in the next version.

**Comment by J-Jamet** [comment] 2018-01-24 19:05
I did several tests but it works without crash for me.
Tested with NextCloud and Nextcloud Dev in API 27 (custom Nextcloud server with docker and no problem)
Can you tell me the version of your android ?

**Comment by J-Jamet** [comment] 2018-02-01 19:04
Can you tell me if the problem is still present with the new version 2.5.0.0beta4 ?

**Comment by func0der** [comment] 2018-02-05 22:05
Nope. Still not working.

Can I produce a crashlog for you somehow?

**Comment by J-Jamet** [comment] 2018-02-08 18:36
It will be a bit complicated. You should connect the phone to the computer and save the logs with ADB that are related to the package com.kunzisoft.keepass
If anyone knows of open source easy tools for monitoring Android crashes remotely...

**Comment by J-Jamet** [comment] 2018-02-13 19:34
If you use the version of the play store you can send me the error report right after the crash. If it is with F-Droid, I do not see other solutions than ADB.

**Comment by ppascher** [comment] 2018-02-16 15:37
Just to add:
Using F-Droid Version 2.5.0.0beta-4-libre I can add entries to my kdbx file hosted on a nextcloud 13 instance without an issue. Phone used is a Galaxy S5 running LineageOS 14.1. Nextcloud App is 13.0.1 from F-Droid.

**Comment by J-Jamet** [comment] 2018-04-06 19:09
I have fixed crashes in version 2.5.0.0beta8 that have probably solved the problem. There was a problem in a key (long in int). I close this issue, if there is still the problem, no worries to open another one.

**Closed by J-Jamet** 2018-04-06 19:09 UTC
Labels: bug

**Comment by justintime4tea** [comment] 2018-04-06 19:44
@J-Jamet If you need a NextCloud instance for testing (or any other purpose) I run my own on DigitalOcean. In the more distant future I want contribute direct NextCloud integration to this project. I <3 NextCloud.

**Comment by J-Jamet** [comment] 2018-04-06 20:25
@justintime4tea thank you for the offer ! I had installed nextcloud locally just to test the application but I can't reproduce the problem. I think it was due to the registration settings of the database.
