### ISSUE TITLE
XmlPullParserException when opening database

### ISSUE THREAD

**Issue by evlo** [Kunzisoft/KeePassDX#890] opened 2021-02-10 11:27 UTC
**Describe the bug**
I get error **XmlPullParserException: wrong event type (position:TEXT UserName@6:110090 in java** ..  like that, when trying to open database, i can't make screenshot and don't know how to see full error in log or something. Only way to get decent error message is to log in landscape, but it closes in seconds

I think it started after I added attachments in keepass for windows, DX broke database, so I overwritten it on windows, but still I get that error when i open it in DX.

I like DX because of it autoType on android.

**KeePass Database**
 - Created with: [e.g Windows KeePass 2.47]
 - Version: ?
 - Location: [dropbox]
 - Size: [250kB]
 - Contains attachment: [YES]
///
**KeePassDX (please complete the following information):**
 - Version: playstore 2.9.12

**Android (please complete the following information):**
 - Device: [e.g. GalaxyS20fe5g]
 - Version: [e.g. 11]

**Additional context**
I'm able to open database on windows

**Comment by J-Jamet** [comment] 2021-02-10 11:37
Your description of the problem is too vague and I can't reproduce the issue with my tests.

Can you upload a test database in order to make the problem visible and by indicating a clear procedure to reproduce it?
Can you explain to me how you conclude that KeePassDX has broken your database?

A XmlPullParserException simply means that there is a problem in reading the XML in the database after decryption but where exactly is the question.

**Comment by evlo** [comment] 2021-02-10 12:00
No, I can't produce sample database as I do not know what exactly is causing the issue. 

I understand XML error is after decoding.

I was able to get the full relevant error:
....
**XmlPullParserException: wrong event type (position:TEXT UserName@6:110090 in java** 
....

I removed one attachment from item with duplicate attachments, it was 40kB one, which was also only larger attachment I had in the database, but error persist.

ad broken: well I started using DX I never had this problem, but it might be issue in dropbox sync as I made quite a lot of saves and url changes as the autofill is finally working, this is not the real issue

**Comment by J-Jamet** [comment] 2021-02-10 12:02
According to the exception, the error comes from a username node. Do you have a username for an entry with special characters or something like that?

**Comment by evlo** [comment] 2021-02-10 12:04
Not that I know of, I'm trying to go trough the last nodes entries I modified or created and recreate them.

**Comment by J-Jamet** [comment] 2021-02-10 12:14
It is possible but I must be able to reproduce the problem. Normally attachments are encoded in Base64 to avoid this kind of problem. Can you tell me if you are using a KDBX4 or KDBX3.1 database? (`Settings` -> `Database settings` -> `Database version`)

**Comment by evlo** [comment] 2021-02-10 12:17
KDBX3.1

**Comment by J-Jamet** [comment] 2021-02-10 12:26
OK, as it is a 3.1 database, the attachments are directly written in the XML.
There may be a character in the binary that causes this exception but in this case it will be complicated to solve because it's the Android base parser that causes the error and I can't really modify it because it's part of your system.
I check that everything is base64 when it's uploaded from KeePassDX but I can't check it from an external source.
What type of binary file did you add?

**Comment by J-Jamet** [comment] 2021-02-10 12:27
It would be nice to be able to prevent this kind of problem anyway, so I would really like to understand the core issue.

**Comment by evlo** [comment] 2021-02-10 12:28
PNG, is there an option to convert database to version 4?

**Comment by J-Jamet** [comment] 2021-02-10 12:32
> is there an option to convert database to version 4?

This is only if you have special conditions in your base, ie: KDF is Argon2.
https://keepass.info/help/kb/kdbx_4.html

**Comment by J-Jamet** [comment] 2021-02-12 10:27
I think the problem comes from Dropbox not being able to fully synchronize the file. I'm closing the issue for now.

**Closed by J-Jamet** 2021-02-12 10:27 UTC
Labels: bug
