### ISSUE TITLE
Issues with colors - Android 8

### ISSUE THREAD

**Issue by frudolph77** [Kunzisoft/KeePassDX#509] opened 2020-04-07 15:23 UTC
After a fresh install there is a problem with the colors in the standard app design.
After the first usage popups all parts that normally have a green background are white, they where green before the popups appear. 
Switching the app design from light to dark and back, does not bring the green areas back. So some part are nearly unreadable on the open database screen.

You have to fully close - kill - the app to bring back the green backgrounds.

Versions
beta28 and newer

**Comment by J-Jamet** [comment] 2020-04-07 18:19
I have already investigated this bug, and I cannot resolve it. For me it is a bug of the AppCompat theme or a display problem on some Android systems after a first launch. As you say, the solution is to kill the application and reopen it. This bug does not depend on a specific version of KeePassDX, I noticed it on Android 8 versions, what is your Android version?

**Comment by frudolph77** [comment] 2020-04-07 21:27
My current Android Version is 8.1. 
I can't remember if I faced this issue earlier on Android 7.

If this isn't an issue with KeePassDX i'm fine with it. 

I only covered this while trying to reproduce another issue, which I can't reproduce any more. I've had KeePassDX installed for a very long time, but when updating from 2.5beta28 to 2.5beta30 the locking of the database wasn't working. But everything is fine, now.

**Comment by Ilithy** [comment] 2020-04-07 22:26
Hi; On my device, (KeepassDX 2.5Beta30, Oneplus 6 under oxygen OS 10. 3, which is Android 10) the problem is almost the same, if I select a dark theme, it's correctly applied, and those immediately, however, if I try to switch back to the light theme, the background remains white, even after correctly locking KeepassDX, and killing the process, at reboot, the application offers a white background, not green (which makes green writing on a white background, which is still perfectly readable) impossible to go back to the green background except by removing the application and reinstalling it.

 I hadn't noticed this bug, because I always use a dark or black background (more economical on OLED screens) but it's not a critical issue, I'm just providing the information.

**Comment by J-Jamet** [comment] 2020-04-11 17:24
I think the problem comes from the material library used. Already I cannot upgrade it because it causes a bug in the views to hide passwords. Like the toolbar of the home page, it is possible that it caused the problem in some cases, I changed the layouts of the home page. You will tell me if the issue is fixed with the new version.

**Comment by Ilithy** [comment] 2020-04-13 09:22
Hello;

As far as I'm concerned, the problem is the same on this version, impossible to restore a green background by applying the light theme after having changed for one of the dark theme, except for a reinstallation of the application.

Thanks

**Comment by J-Jamet** [comment] 2020-04-13 10:19
Okay, thanks for the feedback. In this case, it will be very complicated to fix. :/

**Comment by Ilithy** [comment] 2020-04-13 10:25
With pleasure :)

No problem, it's not something that prevents the software from working well, so nothing to worry about, as I said, I like the black theme, which is perfect in KeepassDX <3

 I remain available if needed for any testing that might be necessary in the future.

**Comment by J-Jamet** [comment] 2020-05-01 11:47
I modified themes and tried to fix import elements. Can you tell me if it's better with version 2.5RC2?

**Comment by Ilithy** [comment] 2020-05-02 08:07
@J-Jamet :
Hello;
Very sorry, same behavior, still can't get back to the green background without re-installing the app.

Thank you very much for your excellent follow-up on this little problem.

**Comment by J-Jamet** [comment] 2020-05-02 08:12
OK, thanks for the feedback. I can't do anything more for the moment. I have to update the Material library, but it adds other bugs (resizing of icons, change of style, etc.) and I'm not even sure that corrects this color problem. I will do this update later but it requires a lot of changes.

**Comment by J-Jamet** [comment] 2021-03-06 17:31
Despite my efforts, I can't find any workaround to this system problem. I updated the libraries and made many tests without result. It only worked if you restart the app, but never the first time on Android Oreo.
When you look in the "About" screen, you also see that the logo doesn't display correctly either (just a black circle). So I don't have any solution, sorry. :raccoon:

**Comment by Ilithy** [comment] 2021-03-07 00:40
> Despite my efforts, I can't find any workaround to this system problem. I updated the libraries and made many tests without result. It only worked if you restart the app, but never the first time on Android Oreo.

Thank you very much for your work, Don't Worry this problem can be ignored. Simply known.

> When you look in the "About" screen, you also see that the logo doesn't display correctly either (just a black circle). So I don't have any solution, sorry.  

I don't have this bug, the KeePassDX logo is displayed correctly.
 (Sorry, I can't provide a screenshot)

In my opinion, this issue could be closed, and reviewed later, if advancement.

Thank you again.

**Comment by J-Jamet** [comment] 2021-12-22 13:10
I've got it! The problem comes from Android 8 which does not support the use of a complex Mipmap drawable.
It makes the whole UI buggy on this version of Android when I use a mipmap with the taptargetview library during an education hint. I replace the icon by a simpler one and it works... :D

**Comment by frudolph77** [comment] 2021-12-27 15:42
Cool, that's fine for other Android 8 users. I've had to switch my phone 3 months ago. I've Android 11 now.

**Closed** 2022-01-18 11:55 UTC
Labels: bug, completed developments, ergonomics
