### ISSUE TITLE
Unable to open a DatabaseV1 with a binary file

### ISSUE THREAD

**Issue by J-Jamet** [Kunzisoft/KeePassDX#398] opened 2019-11-30 16:12 UTC
**Describe the bug**
Databases generated with KeePass 1.35 can not be decrypted.

** Keepass Database **
 - Created with: KeePass 1.35
 - Version: 1
 - Size: 3Mo
 - Contains attachment: Yes

**KeePass DX (please complete the following information):**
 - Version: 2.5.0.0beta24-25

**Additional context**
It seems that the parser can not completely detect the last bits of the stream and does not generate a correct hash.

**Comment by Komic** [comment] 2019-12-07 16:52
Is this the `XmlPullParserException: Unexpected token` bug I've been getting since upgrading to the latest beta?

**Comment by J-Jamet** [comment] 2019-12-08 18:46
In your case no, because v1 database uses bit-to-bit decoding. XML is dedicated to V2 database. You should try to open it with KeePass2, export it to XML and reimport it. I think there is an unreadable binary in your database.

**Comment by Komic** [comment] 2019-12-09 20:23
Weird, it used to work just fine, I just upgraded KPDX. Thanks anyway. (:

**Comment by Ethereum7** [comment] 2019-12-09 23:47
[]() 
Duplicate of `#>` In your case no, because v1 database uses bit-to-bit decoding. XML is dedicated to V2 database. You should try to open it with KeePass2, export it to XML and reimport it. I think there is an unreadable binary in your database.

**Closed** 2020-02-07 21:10 UTC
Labels: bug, completed developments
