### ISSUE TITLE
Fingerprint scanner does not work

### ISSUE THREAD

**Issue by vArhont** [Kunzisoft/KeePassDX#38] opened 2018-03-13 20:40 UTC
Device: Lenovo zuk z1
Android 8.1
With other programs, the fingerprint works perfectly. For example, the andOTP program works.
[spoiler]![screenshot_20180313-223629](https://user-images.githubusercontent.com/36346016/37368658-8af3553e-270f-11e8-88b5-10cb9a4496b5.png)
![screenshot_20180313-223726](https://user-images.githubusercontent.com/36346016/37368664-914c1a06-270f-11e8-8b08-888038135f7a.png)
)[/spoiler]

**Comment by J-Jamet** [comment] 2018-03-13 20:57
The problem is normally fixed in the new version 2.5.0.0beta6, if you use F-Droid, It takes a little time for the server to update. (Link to https://github.com/Kunzisoft/KeePassDX/issues/25)

**Comment by vArhont** [comment] 2018-03-14 06:35
In this version, the same problem, only now when I put my finger on the fingerprint scanner, it seems that it tries to read it with an interval of half a second, but still with an error
![screenshot_20180314-082841](https://user-images.githubusercontent.com/36346016/37386786-9207ba74-2762-11e8-83cd-ebc193ca8b22.png)

**Comment by J-Jamet** [comment] 2018-03-14 10:27
Have you tried to delete the fingerprint keys in the settings?

**Comment by vArhont** [comment] 2018-03-14 16:10
When I press my finger on the fingerprint scanner, the phone vibrates at a half-second interval (this happens when the fingerprint is read), and the inscription "trouble with fingerprints" is constantly updated, sometimes there is an inscription saying that I removed my finger from the scanner too quickly, but this is not so.

**Comment by J-Jamet** [comment] 2018-03-14 20:50
OK, thanks for the description of the problem. I can only test with the emulator because I don't have a real device with fingerprint scanner. Vibrations with small intervals occur to store a password, read a password or both?

**Comment by vArhont** [comment] 2018-03-16 17:25
maybe I can help you with something? is there a way to fix this error so you understand what the problem is? I really like this version of the keepass dx program

**Comment by vArhont** [comment] 2018-03-16 17:26
maybe I can help you with something? is there a way to fix this error so you understand what the problem is? I really like this version of the keepass dx program

**Comment by J-Jamet** [comment] 2018-03-19 01:17
link to #52 
I think now that the problem is the auto re-init of fingerprint after an error. Devices must react differently depending on the model. I'll try to change the exception handling mode.

**Comment by J-Jamet** [comment] 2018-03-25 19:50
Hello, can you tell me if the new version 2.5.0.0beta7 is better for you ? (Normally, lot of problems are now shown in the top box and you have to follow the instructions.)

**Comment by mwip** [comment] 2018-04-01 15:52
After updating to version 2.5.0.0beta7 I had the same error. Fixed of by removing all fingerprints and reentering them as described avove

**Comment by kd8bny** [comment] 2018-04-01 17:55
I think this might be related. Here is the figerprint error I have received with beta 7

![](https://i.imgur.com/i8HLUOG.png)

**Comment by J-Jamet** [comment] 2018-04-01 18:08
It is possible that the refactoring makes the old keystore obsolete and displays a null exception. To solve the problem, the Fingerprint Store must be cleared in 
`Application settings -> [Fingerprint] Delete encryption keys.`
you must then recreate the fingerprints for each password.
Sorry for the manipulation

**Comment by vArhont** [comment] 2018-04-03 12:10
"you must then recreate the fingerprints for each password."
but I can't even create a password for the database

**Comment by J-Jamet** [comment] 2018-04-03 12:24
The password can't yet be changed in the application, just reassign a fingerprint to the current password to unlock the database.

**Comment by J-Jamet** [comment] 2018-04-06 18:59
I close this issue, I'll open a new one if necessary.

**Closed by J-Jamet** 2018-04-06 18:59 UTC
Labels: bug
