### ISSUE TITLE
Two areas for improvement !

### ISSUE THREAD

**Issue by Lanservery** [Kunzisoft/KeePassDX#698] opened 2020-09-13 17:20 UTC
I hope I can copy and paste between the two databases, and I can add my own icons, It will work better.thank you!

**Comment by J-Jamet** [comment] 2020-09-14 08:36
Duplicate of https://github.com/Kunzisoft/KeePassDX/issues/209 and https://github.com/Kunzisoft/KeePassDX/issues/96

**Closed by J-Jamet** 2020-09-14 08:36 UTC
Labels: feature
