### ISSUE TITLE
The Android keyboard appears delayed

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [Kunzisoft/KeePassDX#516] opened 2020-04-14 20:45 UTC
**To Reproduce**
1. open the KeePassDX app for the first time and select a keepass database

2. tap on the password field.

2. the android keyboard app appears, e.g. OpenBoard
https://github.com/dslul/openboard/releases/tag/v1.3

3. but the problem is that the android keyboard appears with a long delay.  It is not fluid.  The problem comes only when the user restarts the KeePassDX app and tap on the password field.

if the user hides the keyboard after point 3 and taps on the password field again, the keyboard will appear smooth and no graphics stutter.

**Keepass Database**
 - Created with: [KeePassDX 2.5RC1]
 - Version: [2]
 - Location: [Internal storage/Download]
 - Size: [7 KB]
 - Contains attachment: [No]

**KeePassDX:**
 - Version: [2.5RC1]
 - Build: [Free]
 - Language: [English]

**Android (please complete the following information):**
 - Device: [Galaxy S10 - Exynos]
 - Version: [Android 10]

**Comment by J-Jamet** [comment] 2020-04-15 07:10
Sorry, but I can't reproduce the problem. I have tested on several of my devices and I have no worries. Have you tried it with other keyboards and other devices?

**Comment by KPSH7AmcSRcfCqdJ** [comment] 2020-04-15 11:01
> Sorry, but I can't reproduce the problem. I have tested on several of my devices and I have no worries. Have you tried it with other keyboards and other devices?

Yes I have tested it on my old Redmi Note 8 with Android 9 and the same keyboard app has no problems.



With other keyboards I also tested it on the Galaxy S10, the standard keyboard (Samsung Keyboard) and on Redmi Note 8 (Gboard).



But I would rather use OpenBoard.



I have already deleted and reinstalled the app, the same problem appears on the Galaxy S10.  I have from memory that a very old KeePassDX version does not have this problem.

But which version I can't remember.

**Comment by J-Jamet** [comment] 2020-04-15 11:11
Okay,
You didn't say if it worked well with the other keyboards on your Samsung Galaxy S10. If so, the problem is more likely with the keyboard. 
Since I cannot reproduce the problem on my side, it will be difficult to know where it comes from. If you tell me that it worked with a previous version, the best is that you retest the old versions and tell me with certainty, which ones work and which ones don't work.

**Comment by KPSH7AmcSRcfCqdJ** [comment] 2020-04-15 11:29
I have tested again on the S10 with the standard keyboard (Samsung Keyboard) and the same problem.

Then I guess I have to re-test all your old KeePassDX versions. :(

**Comment by J-Jamet** [comment] 2020-04-15 11:31
I just thought about it. But try disabling biometric unlock in the settings and try again.

**Comment by KPSH7AmcSRcfCqdJ** [comment] 2020-04-15 11:42
I have disabled the biometric setting in KeePassDX and use only the password to unlock it. Same problem.

**Comment by J-Jamet** [comment] 2020-04-15 11:44
Okay, so the biometric isn't the problem. I have no more idea for the moment.

**Comment by KPSH7AmcSRcfCqdJ** [comment] 2020-04-15 12:06
Hello,

I found it, this version no problems.

https://github.com/Kunzisoft/KeePassDX/releases/tag/2.5.0.0beta22

Since KeePassDX 2.5.0.0beta23 you have changed the procedure, I see that when opening the app (database previously selected) the keyboard is not shown automatically, but the user has to manually tap the password field to get the keyboard.

This procedure in beta22 (keyboard comes automatically without tapping the password field manually) works on both Android devices without problems, both fluently. But since beta23 a new procedure (manual tapping on the password field, then the keyboard appears) it is only fluid on my Redmi device.

**Comment by J-Jamet** [comment] 2020-04-15 13:08
Okay, now I understand, before you just didn't have the keyboard display. But focus the view is useful for users who use ChromeBook, so i can't really remove the focus at start.
Is the bug really annoying? Because I think that the problem will be very difficult to solve since I do nothing special; It's just automatic focus. At worst I can add a setting to prevent this focus.
Do you also have the problem with other applications?

**Comment by KPSH7AmcSRcfCqdJ** [comment] 2020-04-15 14:21
The new procedure (manual tapping on the password field, then the keyboard appears) since beta23 is the same as for other KeePass apps, e.g. KeePassDroid. https://github.com/bpellin/keepassdroid/releases/tag/v2.5.7

I have to manually tap on the password field, then the Android keyboard appears.



The problem is that with KeePassDX the Android keyboard is delayed.  I tap on the password field and the keyboard appears, but delayed (it also jerks a little).  It's not fluid, as usual.  It feels similar to games that have a lag (no constant FPS or something like that).  I only know that it is not fluid.  My friends see it that the Android keyboard comes with a time delay and when it comes, it's a bit laggy.  No matter which keyboard I use, GBoard, Samsung Keyboard or OpenBoard.



Just like I wrote in the first post under reproduce.

The problem is only on Galaxy S10.  :(

Strangely, this problem doesn't exist on beta22 with old procedure or as you say automatic focus. Where the password field is automatically selected when you open the KeePassDX app and the Android keyboard appears automatically (no lag, no delay).

**Comment by KPSH7AmcSRcfCqdJ** [comment] 2020-04-15 16:32
I have no problems with KeePassDroid.

**Comment by Rumpotkimhy** [comment] 2020-06-25 00:59
I have the same problem with my Samsung Galaxy S10+ and Android 10 + OneUI 2.1.

Tested with the KeePassDX 2.7.  There is really a short delay.

How can I help to fix the problem?

**Comment by J-Jamet** [comment] 2020-11-01 19:09
I changed the UI in version 2.9, you will tell me if it changes anything for this issue.

**Comment by J-Jamet** [comment] 2021-08-31 08:56
I close this issue, I reworked the layout and implemented the automatic keyboard opening in version 3.0.0.

**Closed by J-Jamet** 2021-08-31 08:56 UTC
Labels: bug
