### ISSUE TITLE
Magikeyboard doesn't work properly

### ISSUE THREAD

**Issue by smnthermes** [Kunzisoft/KeePassDX#351] opened 2019-10-02 14:38 UTC
Steps to reproduce:
1. Change to Magikeyboard
2. Open the database and insert its master password
3. Select a password
After switching back to the anterior app, the selected password doesn't appear on Magikeyboard.

**Comment by J-Jamet** [comment] 2019-10-03 09:42
I can't reproduce this issue, can you tell me what is your Android, app version and device?

**Comment by J-Jamet** [comment] 2019-10-04 16:02
Without further information, I think you are closing the database and the previously selected entry is delete from the MagiKeyboard : 
- Automatically by timeout
- or By pressing the back button when the setting "Press Back on root to lock" is enabled
- or by locking the database

**Comment by J-Jamet** [comment] 2019-11-12 12:16
Unable to reproduce the problem and no new information. I close the issue.

**Closed by J-Jamet** 2019-11-12 12:16 UTC
Labels: bug, invalid
