### ISSUE TITLE
Permission denial

### ISSUE THREAD

**Issue by Konfetti030** [Kunzisoft/KeePassDX#957] opened 2021-04-07 17:43 UTC
Since some days I get error message starting the app says user removed permission denial.
I didn't do anything and I can't allow permission to storage.

**Comment by J-Jamet** [comment] 2021-04-07 18:04
Please be more specific in writing your bug, you didn't fill in the template correctly so I have no context to help you. https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Please indicate the file manager used, the database version, the application version and the characteristics of your device.

**Comment by Ilithy** [comment] 2021-04-07 20:29
Hi,

> I didn't do anything and I can't allow permission to storage

It seems to be strange, if you long click on the application icon, then on the information icon (normally an i surrounded by a circle), in the permissions (Click on it to access), you click on the permission "access to storage" or simply "Storage", here you should have the option to allow or not. Is this not the case?

**Comment by Konfetti030** [comment] 2021-04-07 21:04
There isn't even a possibility to choose allow permission because it's
greyed out.

Can I uninstall the app and reinstall it or do I lose my database?

Ilithy ***@***.***> schrieb am Mi., 7. Apr. 2021, 22:30:

**Comment by Ilithy** [comment] 2021-04-07 22:39
@Konfetti030 KeepassDX does not manage the database, it only allows you to open and edit it (and to modify its parameters), so no, there is no risk of losing it,

PS: remember to note its location if you don't know it.

**Comment by J-Jamet** [comment] 2021-04-08 05:45
@Konfetti030  You haven't read the wiki and you don't describe any context. I close the issue. The problem is probably with your file manager.

Permissions are not required, if you want to add them, recompile the application.
https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync

Make backups of your database file regularly.
https://github.com/Kunzisoft/KeePassDX/wiki/Backup

**Closed by J-Jamet** 2021-04-08 05:45 UTC
Labels: bug, invalid
