### ISSUE TITLE
Autofill is not searching for website URL using Microsoft Edge browser

### ISSUE THREAD

**Issue by tehniemer** [Kunzisoft/KeePassDX#753] opened 2020-10-17 15:52 UTC
**Describe the bug**
Autofill does not recognize the URL when invoked from Microsoft edge browser.

**To Reproduce**
1. Invoke autofill from a website in Microsoft edge.
2. Autofill entry is looking for com.microsoft.emmx instead of URL of website it was called from.

**Expected behavior**
Autofill should search for and find URL in key pass database entry.

** Keepass Database **
 - Created with: [Windows KeePass 2.42]
 - Version: [2]
 - Location: [Remote file retrieved with OneDrive app]
 - Size: []
 - Contains attachment: [No]

**KeePassDX (please complete the following information):**
 - Version: [2.8.7]
 - Build: [Free]
 - Language: [English]

**Android (please complete the following information):**
 - Device: [OnePlus 6]
 - Version: [10.3.6]

**Additional context**
 - Browser for Autofill: [Microsoft Edge 45.09.4.5079]

**Comment by J-Jamet** [comment] 2020-10-18 08:51
Linked to https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-703770140

I think the problem is already fixed with #551.
I will check this for the next version.

**Comment by J-Jamet** [comment] 2020-10-18 12:03
Confirmed, fixed with #551

**Comment by tehniemer** [comment] 2020-10-18 12:40
Awesome! Just bought a pro licence, thanks for all your work.

**Comment by J-Jamet** [comment] 2020-10-18 13:37
Thank you! (⌒．⌒)

**Closed** 2020-11-01 18:56 UTC
Labels: bug, completed developments
