### ISSUE TITLE
Database v4 saved on KeePassDX v2.8.4 can't be opened by Keepass2Android

### ISSUE THREAD

**Issue by hokonch** [Kunzisoft/KeePassDX#708] opened 2020-09-18 12:13 UTC
**Describe the bug**
Warning shown on Keepass2Android
> An error occured: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

**KeePassDX :**
 - Version: 2.8.4 (not reproducible in 2.8.3)

**Additional context**
KeeWeb & KeePassXC can open the Database without problems. (Not tested on KeePass)

**Comment by J-Jamet** [comment] 2020-09-18 12:21
Linked to https://github.com/Kunzisoft/KeePassDX/issues/691

Try to replace line 641 in https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/java/com/kunzisoft/keepass/database/element/database/DatabaseKDBX.kt with `const val BASE_64_FLAG = Base64.NO_PADDING or Base64.NO_WRAP`
I think it comes from TAG NO_PADDING.

**Comment by J-Jamet** [comment] 2020-09-18 12:55
I just checked by recompiling the code without the TAG and it happens but I don't know why, I'm still looking to find out where the problem is coming from.

**Comment by J-Jamet** [comment] 2020-09-18 13:32
Honestly I'm lost, I made two compilations, with the free and pro variant. A save with free database does not show the error on K2A. But a save on pro database shows error on K2A.

**Comment by J-Jamet** [comment] 2020-09-18 14:10
In fact it is a cache problem, it is indeed the problem of TAG but it is necessary to clear the cache for the changes to take effect.

**Comment by J-Jamet** [comment] 2020-09-18 14:24
Fixed in release 2.8.5

**Closed** 2020-09-18 14:23 UTC
Labels: bug, completed developments
