### ISSUE TITLE
Support otpauth://steam/Steam link

### ISSUE THREAD

**Issue by weirdal3333** [Kunzisoft/KeePassDX#1289] opened 2022-04-10 10:46 UTC
**Is your feature request related to a problem? Please describe.**
Support for Steam key authentication is available in the desktop app. It is not yet available in the mobile app. It is extremely simple to support!

**Describe the solution you'd like**
Please add steam authenticator to the list of supported OTP types!

**Describe alternatives you've considered**
I am currently using Aegis authenticator for otp codes but want to be able to use KeePass for everything!

**Additional context**

**Comment by weirdal3333** [comment] 2022-04-10 10:48
I'd like to clarify that this is a MOBILE device issue, not a desktop issue. The desktop version works fine. Mobile just shows a blank space where the otp token ought to be.

**Comment by J-Jamet** [comment] 2022-04-10 11:31
> It is extremely simple to support!

Ho really.

But it's funny I don't see your pull request, if you had studied how it works, you would have seen that it's not that easy and more important: it's already implemented!

And you know, in this case it is also easy to comply with OTP standards. You said that to Steam team?


> Mobile just shows a blank space where the otp token ought to be.

I can't reproduce this issue. Can you be more precise on your steps to reproduce this behavior?

**Comment by J-Jamet** [comment] 2022-04-10 11:33
https://github.com/Kunzisoft/KeePassDX/wiki/OTP#totp-steam

https://github.com/Kunzisoft/KeePassDX/wiki/FAQ#why-not-give-direct-access-to-alternative-themes-or-not-standardized-protocols

**Comment by weirdal3333** [comment] 2022-04-10 11:50
I'd like to clarify, again, that this is a MOBILE device issue, not a desktop issue.

The latest version of this app in the fdroid app store is 3.3.3, which was last updated on March 28th. It still has no support. 
I have opened my desktop keepassDX database (which, again, has no issues whatsoever with showing the steam key on my PC) on a fresh install of this app via multiple Android devices.

I might remind you, that this has ALREADY been implemented in the desktop version, so that's why I say porting it should be easy.

I'm making an issue instead of a pull request because I don't 100% know how to code Android apps. I am very sorry that what I know isn't good enough for you.

**Comment by J-Jamet** [comment] 2022-04-10 12:49
> I'd like to clarify, again, that this is a MOBILE device issue, not a desktop issue.

In that case, at least indicate which device you have, do you have a chrome OS? I don't have that kind of device, so it's possible that there are different behaviors but the token generation doesn't depend on a specific display, so I don't understand, it shouldn't work for other TOTP tokens either.

> The latest version of this app in the fdroid app store is 3.3.3, which was last updated on March 28th. It still has no support.

I'm sure it works since I'm using F-Droid 3.3.3 and I can generate Steam tokens.

> I might remind you, that this has ALREADY been implemented in the desktop version, so that's why I say porting it should be easy.

I repeat, the code of the generation of Token steam is already implemented In KeePassDX, since almost the beginning of the implementation of TOTP, I am sure it is me who made the code and it wasn't that easy...

I also repeat, you can select Steam if you have the Pro version because it is not a standardized protocol and I don't like this kind of practice of not following the standards (RFC2638). If every new closed service redefines standards it closes protocols and gives more work to developers.

**Comment by J-Jamet** [comment] 2022-04-10 12:55
As it seems to be a bug on your device, please fill in this template correctly: https://github.com/Kunzisoft/KeePassDX/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by weirdal3333** [comment] 2022-04-10 13:15
There is no pro version on the fdroid store. I am using a OnePlus Nord
N200, which runs Android 11. The keepass database that was made is version
2 kbdx3.1.
The token that's saved in the field starts with `otpauth://steam/Steam`.

**Comment by J-Jamet** [comment] 2022-04-10 13:27
`otpauth://steam/Steam` is not a standard otpauth link but an otp link modified for steam. 
More time to adapt a non-standardized thing. Yippee...

https://github.com/beemdevelopment/Aegis/issues/343

**Comment by weirdal3333** [comment] 2022-04-10 13:37
I read the part of your code that deals with the OTP keys, and read the
links that you provided. I had imported my keys from Aegis, and apparently
Aegis uses a different format for steam keys than this app.
I changed that first part from `otpauth://steam/Steam` to
`otpauth://totp/Steam`, and now it works. Very odd that it works with
`otpauth://steam/Steam` on desktop but not on Android. I wonder if this is
actually an issue with how Aegis imports things 🤔

Anyway, thank you for pointing me in the right direction with those links!
I'll mark this issue closed in a minute

**Comment by J-Jamet** [comment] 2022-04-10 13:46
> Anyway, thank you for pointing me in the right direction with those links!

The most important thing is to understand the problem. But don't hesitate to write down all the steps from the beginning because it is difficult to reproduce a bug. ;)

> I'll mark this issue closed if you want me to. In my opinion, we should stay as close to the standard as we can.

Don't close the issue, it will allow me to see that this feature is not implemented.

>  This is originally and continuously steam's fault.

Clearly :dagger:

**Closed** 2024-11-18 11:04 UTC
Labels: feature, completed developments
