### ISSUE TITLE
KeePassDX 2.8.6 crashes on db opening (F-Droid)

### ISSUE THREAD

**Issue by CaseOf** [Kunzisoft/KeePassDX#733] opened 2020-09-30 08:52 UTC
Hello,
I updated KeePassDX to 2.8.6 from F-Droid and since unlockung database when opening it after giving passphrase make the app crash.
I'm running a Nexus 6 on LineageOS 17.1.

**Comment by J-Jamet** [comment] 2020-09-30 09:20
The problem is already fixed in version 2.8.7. Same as https://github.com/Kunzisoft/KeePassDX/issues/722

**Comment by J-Jamet** [comment] 2020-09-30 09:23
You just have to wait for the update on F-Droid

**Comment by hokonch** [comment] 2020-09-30 09:55
F-Droid has already tried to build [KeePassDX v2.8.7](https://f-droid.org/wiki/index.php?title=com.kunzisoft.keepass.libre/lastbuild_43&action=history) twice, but both of the builds were failed due to F-Droid's long-time unfixed bug.
This bug seems to have occurred frequently recently. For example, F-Droid has failed to build KeePassDroid for a month.

**Comment by J-Jamet** [comment] 2020-09-30 09:57
:cry:

**Comment by J-Jamet** [comment] 2020-09-30 10:40
I made a request to remove the release 2.8.6 from F-Droid: https://gitlab.com/fdroid/fdroiddata/-/issues/2180

**Comment by mat-l** [comment] 2020-09-30 19:45
The downgrade option via F-Droid is not working for me. It throws always an error that it wss not able to install the app.

Do you have manual builds somewhere, which one can download in the meanwhile until F-Droid builds are working again?

**Comment by J-Jamet** [comment] 2020-09-30 19:57
Yes, You can manually download the free version: https://github.com/Kunzisoft/KeePassDX/releases/tag/2.8.7

**Comment by mat-l** [comment] 2020-09-30 20:07
> Yes, You can manually download the free version: https://github.com/Kunzisoft/KeePassDX/releases/tag/2.8.7

Thanks you for your work and the link to the assets 🙏🏼

**Comment by LittleEntity** [comment] 2020-10-01 05:23
> Yes, You can manually download the free version: https://github.com/Kunzisoft/KeePassDX/releases/tag/2.8.7
YAY! Thankyou very much. Where can i hand you a coffee? Does the F-Droid donation button work for you?

**Comment by adatum** [comment] 2020-10-01 06:07
Same here with KeePassDX 2.8.6, which was an upgrade on 9/29/20. After entering the master password, the app seemed to just return to the password entry screen. Maybe a crash. I was going mad re-re-re-entering the password, but it did not complain of incorrect credentials. 

I verified that my password and database were ok with Keepass2Android. 

Finally downgrading to KeePassDX 2.8.3 worked and the app functions properly now. 

Running /e/ based on LineageOS 16 on a LG G4.

**Comment by borrougagnou** [comment] 2020-10-01 08:50
I think I'll do the same, it's impossible for me to use 2.8.6 and I don't want switch to github...

**Comment by pstorch** [comment] 2020-10-01 18:08
> The downgrade option via F-Droid is not working for me. It throws always an error that it is not able to install the app.
> 
> Do you have manual builds somewhere, which one can download in the meanwhile until F-Droid builds are working again?

Had the same issue. I manually uninstalled the 2.8.6 version, then I could install the previous version 2.8.3.

**Comment by hokonch** [comment] 2020-10-02 15:25
Good news. The build of v2.8.7 seems to have been successful, so it will be released on F-Droid in a day or two.
https://f-droid.org/wiki/page/com.kunzisoft.keepass.libre/lastbuild_43

**Comment by H2172** [comment] 2020-10-04 11:36
Confirmed: This morning my F-Droid notified me of the 2.8.7 update. Have installed it, and the 2.8.6 crash is gone.

**Closed** 2020-10-04 11:37 UTC
Labels: bug, completed developments, question
