### ISSUE TITLE
git tree : duplicate entries on push

### ISSUE THREAD

**Issue by SvSky** [Kunzisoft/KeePassDX#1333] opened 2022-05-17 09:01 UTC
Hello,

i try to push the master branch to another repo but i can't and have this error.

 
git push <repo_name> master (no master branch on this repo, but master.old (2.5beta30)): 
Décompte des objets: 91706, fait.
Delta compression using up to 8 threads.
Compression des objets: 100% (19007/19007), fait.
remote: error: object ffa998510f3e1206ac95a4a3e35e25e3f4017adb: duplicateEntries: contains duplicate file entries
remote: fatal: fsck error in packed object
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500 Internal Server Error
Écriture des objets: 100% (91706/91706), 53.33 MiB | 14.55 MiB/s, fait.
Total 91706 (delta 61011), reused 91690 (delta 61008)
error: le dépaquetage a échoué : index-pack abnormal exit
Everything up-to-date

git fsck --full : 
Vérification des répertoires d'objet: 100% (256/256), fait.
error in tree b7a0b493966f9077f6fcd7de37244699bb73615e: duplicateEntries: contains duplicate file entries
error in tree 2f5da62ad954c1d90c4618f1277d0f5474bed327: duplicateEntries: contains duplicate file entries
error in tree ffa998510f3e1206ac95a4a3e35e25e3f4017adb: duplicateEntries: contains duplicate file entries
Vérification des objets: 100% (92209/92209), fait.

git ls-tree <hash> --full-tree -rt -l > <hash>.txt :
[2f5da62ad954c1d90c4618f1277d0f5474bed327.txt](https://github.com/Kunzisoft/KeePassDX/files/8706721/2f5da62ad954c1d90c4618f1277d0f5474bed327.txt)
[b7a0b493966f9077f6fcd7de37244699bb73615e.txt](https://github.com/Kunzisoft/KeePassDX/files/8706724/b7a0b493966f9077f6fcd7de37244699bb73615e.txt)
[ffa998510f3e1206ac95a4a3e35e25e3f4017adb.txt](https://github.com/Kunzisoft/KeePassDX/files/8706727/ffa998510f3e1206ac95a4a3e35e25e3f4017adb.txt)

Thank you

**Comment by J-Jamet** [comment] 2022-05-18 12:04
Issue comes from old repo : https://github.com/bpellin/keepassdroid/issues/441
I guess you already looked at this thread:
https://stackoverflow.com/questions/13178720/tree-contains-duplicate-file-entries
https://stackoverflow.com/questions/10931954/git-tree-contains-duplicate-file-entries

To remove _dangling blob & commit_ : `git reflog expire --expire=now --all && git gc --prune=now --aggressive`

I think Brian did some tests on Windows and committed files with the same names but different case. I tried several commands to fix these trees but I would have to rewrite the whole history to make it work. So it will stay like this. What are you trying to push and on which repo, I don't see any public project on your github.

**Comment by SvSky** [comment] 2023-04-17 07:47
Hello,
I try to push on a gitlab repo (work environment)

It's an old issue but i solve it :
mkdir KeePassDXtmp
cd KeePassDXtmp
git init
cd ../KeePassDX
git fast-export --all | (cd ../KeePassDXtmp && git fast-import)
cd ../KeePassDXtmp
git remote add (my repo)
git push 

and it work

**Comment by licaon-kter** [comment] 2023-09-14 08:16
Seeing the same issue on clone too: https://monitor.f-droid.org/builds/log/com.kunzisoft.keepass.libre/125#site-footer

**Comment by J-Jamet** [comment] 2023-09-16 08:57
> Hello, I try to push on a gitlab repo (work environment)
> 
> It's an old issue but i solve it : mkdir KeePassDXtmp cd KeePassDXtmp git init cd ../KeePassDX git fast-export --all | (cd ../KeePassDXtmp && git fast-import) cd ../KeePassDXtmp git remote add (my repo) git push
> 
> and it worked

I can't afford to rewrite the history and change the hashes of all the commits.
I need to find a solution that only solves the problem at the level of the duplicate tree.

I used to have no trouble building on F-Droid with this repo, so something must have changed.

**Comment by cjc7373** [comment] 2023-09-17 11:37
AFAIK the only way to fix this is to rewrite the whole history. Github/F-droid server has some git settings like `transfer.fsckObjects` set, so they run `git fsck` when reciveing/fetching objects, that's why the error happens.

I think f-droid people may tweak some settings to make the clone success. The [link posted above](https://gitlab.com/fdroid/fdroidserver/-/issues/1084) already pointed out some ways to ignore this kind of error.

**Comment by licaon-kter** [comment] 2023-09-17 20:48
Actually it does not, as the setting is VM wise, the first clone fails.

For other apps the issue was with some submodule-d repo that was cloned later hence we could have controlled that manually.

For now there's no solution, F-Droid wise...

**Comment by shuvashish76** [comment] 2023-10-08 10:49
Since the app is not set up for reproducible builds at F-Droid, we can't even use izzyrepo for updates. So basically F-Droid users stuck with v3.5.1.

**Comment by IzzySoft** [comment] 2023-10-09 20:14
I'll pick up the version offered here meanwhile as it doesn't conflict (thanks @shuvashish76 for the [detailed report](https://gitlab.com/IzzyOnDroid/repo/-/issues/451)!) I'll also pick up Fastlane with future releases, but for now have to skip `full_description.txt` due to some formatting issue: my repo renders it via standard (not Github-flavored) Markdown, so it needs an empty line also before the bullet-point list (and ideally also the space in front of each bullet point removed). If you can adjust that and let me know afterwards @J-Jamet, I'd pick it up as well.

**Comment by GalaxySnail** [comment] 2023-10-24 23:42
> Maybe with a git replace by deleting the old history and pointing it to the new one, but I don't know if that will solve the problem and keep the hashes.

Unfortunately AFAIK it's not possible to fix it without rewriting the history. According to [the documentation](https://git-scm.com/docs/git-replace), `git replace` has no effect on `git fsck`.

Is it currently possible to configure `fsck.skipList` or `fsck.duplicateEntries ignore` on f-droid?

**Comment by eighthave** [comment] 2023-11-13 11:52
https://gitlab.com/fdroid/fdroid-bootstrap-buildserver/-/merge_requests/30 will give the _fdroiddata_ maintainers the power to add per-commit exceptions to the _fsck_ checks.  It seems like there will be three commit IDs the KeePassDX maintainers should add to the new files, e.g. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14014

**Closed** 2024-11-17 14:03 UTC
Labels: bug

**Comment by IzzySoft** [comment] 2024-11-27 21:54
Not sure how comes, but meanwhile there seems to be a 4th commit hash:

```
+ git clone -b 4.1.1 -- https://github.com/Kunzisoft/KeePassDX.git /build/repo
Cloning into '/build/repo'...
error: object b7a0b493966f9077f6fcd7de37244699bb73615e: duplicateEntries: contains duplicate file entries
fatal: fsck error in packed object
fatal: fetch-pack: invalid index-pack output
```

I just wonder that this is not in F-Droid's skip list, but they could still build 4.1.1…
