### ISSUE TITLE
Black screen and freezes with Samsung

### ISSUE THREAD

**Issue by dieharddan** [Kunzisoft/KeePassDX#1273] opened 2022-03-13 03:00 UTC
Hello used this for a few years on my lg v30 and always worked flawless (thank you). But I switched to a samsung galaxy note 9, and when i open my database it black screens for 10 seconds and thrn freezes on the screen to enter the database password, eventually i can get the keyboard up and get into the database but it will have episodes of freezing. Not sure if this is just my phone or all note 9s or samsung devices

**Comment by J-Jamet** [comment] 2022-03-13 16:37
Does this happen with a newly created database or only with yours. I can't reproduce your problem because I don't have your device so I will have to debug by deduction.

**Comment by dieharddan** [comment] 2022-03-13 18:05
I just tried with a new database and still have the issue

**Comment by J-Jamet** [comment] 2022-03-14 08:41
Have you updated the system on your new device? Because I have no idea where the problem in the application is coming from.

**Comment by Ilithy** [comment] 2022-03-14 10:52
This may sound silly but, have you tried rebooting your device?

**Comment by dieharddan** [comment] 2022-03-16 00:37
The device was up to date when I got it. I have rebooted. This phone does not have google play servicea or framework, if that makes any difference it didnt on my V30 which was also degoogled

**Comment by J-Jamet** [comment] 2022-03-18 11:00
Your problem seems to be the same as #1269, problem that affects Samsung devices.
I will continue the investigation and update the other discussion.

**Comment by J-Jamet** [comment] 2022-03-19 23:19
Do you use advanced unlocking with the device credential?

**Comment by dieharddan** [comment] 2022-03-20 16:07
No, I only use a password

**Comment by J-Jamet** [comment] 2022-03-23 19:08
Since this seems to be a problem in the OS Keystore, the easiest workaround is to not enable biometric solutions by default. From now on it will be necessary to activate these features manually, which will allow for a finer granularity of the problems.

**Comment by J-Jamet** [comment] 2022-03-26 15:40
I close this issue, we can continue to discuss on #1269

**Closed by J-Jamet** 2022-03-26 15:40 UTC
Labels: bug, completed developments
