### ISSUE TITLE
Error when Reloading Database

### ISSUE THREAD

**Issue by GreatNewHope** [Kunzisoft/KeePassDX#877] opened 2021-01-25 17:32 UTC
**Describe the bug**
When I update a database hosted in Google Drive in my computer, I go to my KeepassDX to check if it is aware of the new register. The new register is not present and thus I click "Reload Database". The following error comes up.

java.io.FileNotFoundException: StorageFileLoadException[download_unavailable]
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1162)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:999)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:719)
	at com.kunzisoft.keepass.utils.UriUtil.getUriInputStream(UriUtil.kt:71)
	at com.kunzisoft.keepass.database.element.Database.readDatabaseStream(Database.kt:336)
	at com.kunzisoft.keepass.database.element.Database.reloadData(Database.kt:434)
	at com.kunzisoft.keepass.database.action.ReloadDatabaseRunnable.onActionRun(ReloadDatabaseRunnable.kt:44)
	at com.kunzisoft.keepass.tasks.ActionRunnable.run(ActionRunnable.kt:35)
	at com.kunzisoft.keepass.notifications.DatabaseTaskNotificationService$executeAction$2$invokeSuspend$$inlined$apply$lambda$1.invokeSuspend(DatabaseTaskNotificationService.kt:441)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Expected behavior**
Update the database and be able to see the new value inserted by the computer in the cloud database. 

**KeePass Database**
 - Created with: Windows KeePass 2.47
 - Version: 2
 - Location: Remote file retrieved with GDrive app
 - Size: 8kb
 - Contains attachment: No

**KeePassDX:**
 - Version: 2.9.12 Built from development branch on last commit from 22 january
 - Language: Spanish

**Android (please complete the following information):**
 - Device: xiaomi redmi 4x
 - Version: miui 11

**Comment by J-Jamet** [comment] 2021-01-25 17:42
I will capturing the exception to display an error message indicating that the file does not exist, but I can't satisfy the behavior you expect, because by definition if there is this error it means that the file is not available.

**Comment by GreatNewHope** [comment] 2021-01-26 09:00
I understand. Thank you very much!

**Comment by J-Jamet** [comment] 2021-01-26 10:19
I just checked and I'm pretty sure I've handled this kind of case in commit [_9eb66face5aafad115827d15ec3c9d1d2697ae3f_](https://github.com/Kunzisoft/KeePassDX/commit/9eb66face5aafad115827d15ec3c9d1d2697ae3f).
Have you tested version 1.9.12 currently in production?

**Comment by GreatNewHope** [comment] 2021-01-26 11:34
mmmm doesn't seem to catch the exception on 2.9.12. The exception still crashes the app

**Comment by J-Jamet** [comment] 2021-01-26 12:51
I can't reproduce the problem at home, the application doesn't crash.
If there is an error in the logs it is normal because the file cannot be loaded, the current behavior of 2.9.12 closes the current screen and database but it's not a crash.
I can changed this behavior in the develop branch to display only the error message but a click on an element will close the database anyway.
In any case, it will still not be possible to make a reload.

**Comment by J-Jamet** [comment] 2021-01-26 13:27
I just added a Toast and fixed the closing animations by just calling finish(). It will be less visually confused.

**Comment by J-Jamet** [comment] 2021-01-26 13:43
I also transformed the exceptions to standardize them as LoadDatabaseException, normally it's OK.

**Comment by GreatNewHope** [comment] 2021-01-27 08:40
ok Thanks! 😄

**Closed** 2021-02-15 11:55 UTC
Labels: bug, completed developments
