### ISSUE TITLE
Autofill: Recognize distinct hyphenated domain names

### ISSUE THREAD

**Issue by JJohnGreenSr** [Kunzisoft/KeePassDX#1105] opened 2021-09-14 13:46 UTC
**Describe the bug**
Not sure if I worded the title right, but whenever I log in to my Microsoft Outlook email, I'm sent to login.live.com. But KeePassDX also lists accounts for forums.nba-live.com (a site for basketball discussion)

**To Reproduce**
1. Have an account for login.live.com
2. Have an account for forums.nba-live.com
3. Go to outlook.com
4. Tap sign in button, which redirects you to login.live.com
5. Tap Sign in via KeePassDX button on keyboard
6. Unlock database
7. Both account entries should be listed on autofill

**Expected behavior**
Only the one for login.live.com should be listed on the autofill section of my keyboard.

**KeePass Database**
 - Created with: KeePass 2 (looking at settings)
 - Version: KDBX 4.0
 - Location: Remote file retrieved with Nextcloud app
 - Size: Maximum size 6 MiB
 - Contains attachment: No

**KeePassDX (please complete the following information):**
 - Version: 2.10.5
 - Build: libre
 - Language: English

**Android (please complete the following information):**
 - Device: Galaxy A11
 - Version: 11

**Additional context**
 - Browser for Autofill: Brave 1.29.79, Chromium 93.0.4577.63

**Comment by J-Jamet** [comment] 2021-09-14 14:04
KeePassDX cannot guess that credentials from one domain are running on another domain. You just have to fill a new custom field in the basketball site entry, to add `login.live.com`.

**Comment by uduerholz** [comment] 2021-09-16 12:14
I guess what happens here is the following:
Subdomain search is not enabled per default.
When you open a URL with a domain *.live.com the autosearch for the autofill will search the database for entries that _contain_ the string "live.com" in either the URL, title or notes:

`            return stringToCheck.isNotEmpty()
                    && stringToCheck.contains(
                        searchParameters.searchQuery, true)`

So an entry with URL "forums.nba-live.com" will also match.

**Comment by uduerholz** [comment] 2021-09-20 11:26
@J-Jamet Did you read my comment? What do you think?

**Comment by J-Jamet** [comment] 2021-09-20 13:30
Yes you're right, I got the problem backwards.

**Comment by J-Jamet** [comment] 2021-09-22 13:04
My first idea to solve this problem is to add a "." to search as a prefix, but it won't work if there is no subdomain. So I think it's better to leave the current behavior, just select the right domain when clicking. Unless you have another idea for fixing this bug.

**Comment by uduerholz** [comment] 2021-09-22 14:34
I had a look at the code last week and was a bit surprised how much effort is made to determine the "public suffix" of the domain (which is not necessarily the top level domain, e.g. co.uk is a public suffix).
What if only the complete domain name is considered a match, no matter if a sub domain is present or not?
Why is it the default that subdomains are disregarded in the search?

**Comment by J-Jamet** [comment] 2021-09-22 17:40
I don't have the whole subject in mind anymore but I know that it solves specific problems, I had done many tests.

In one case there will be URL redirection, in other cases not, so for example if you register a url with `www` and the next time you go to the same site without `www`, it will not work. I also know that websites use subdomains only for login. (Same thing for mobile version `.m` if a database is shared with a desktop version). Some sites even use lots of subdomains to handle large-scale simultaneous connections, so it won't be the same subdomain for every login.
So it requires the user to register all login URLs, which would be horrible.
but without searching for the subdomain, it makes things much easier for the user.
Unfortunately, there will always be special cases.

Link https://github.com/Kunzisoft/KeePassDX/issues/1044 https://github.com/Kunzisoft/KeePassDX/issues/728 https://github.com/Kunzisoft/KeePassDX/issues/584 https://github.com/Kunzisoft/KeePassDX/issues/614

**Comment by uduerholz** [comment] 2021-09-22 19:20
I see, so probably it's better to leave it as it is.

**Comment by JJohnGreenSr** [comment] 2021-10-02 10:47
I know that's often the case for subdomains with periods (for example en.m.wikipedia.org has the same login and domain as en.wikipedia.org), but I don't think that applies to hyphens. live.com and nba-live.com are completely separate domains with separate ownership and Whois registrations

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by J-Jamet** [comment] 2021-10-03 16:13
We can manually see that they are different domains in your case, but the search doesn't know that since "live.com" is searched and I don't see a method to solve this problem without breaking something else.

**Comment by zinalili** [comment] 2022-08-10 16:27
J-Jamet, could you add an option to only look up matches in URL section for autofill suggestions?

**Comment by J-Jamet** [comment] 2024-11-08 20:10
I have found a satisfactory solution, the idea is to check the URL field of the entry if :
- It is rigorously exact to the domain (ie: _domain.org_)
- It's a string that ends in the domain with a “.”, which indicates a sub-domain (ie: _subdomain.domain.org_)
- It's a string that ends in the domain with a “/”, meaning that the protocol is present. (ie: _https;//domain.org_)
- Other domains containing the domain name are not checked. (ie: _myootherdomain.org_)

This will be in the next release. Please let me know if you see any regressions with your URLs.

**Comment by J-Jamet** [comment] 2024-11-18 11:05
Please retest with version 4.1.0 and let me know if the problem has been solved.

**Closed by J-Jamet** 2024-11-18 11:05 UTC
Labels: bug, completed developments

**Comment by J-Jamet** [comment] 2024-11-19 20:08
Actually, this issue is fixed but not the #1820. I thought it would solve both at the same time, but no.

**Comment by J-Jamet** [comment] 2024-11-19 20:31
I've just figured out what's wrong, I've tested it but I don't know why, the SearchHelper line contains \\\ that have been added line https://github.com/Kunzisoft/KeePassDX/blob/ada8f74e2c4f2ac44f96d546b890fd1ab660a0a6/database/src/main/java/com/kunzisoft/keepass/database/search/SearchHelper.kt#L157
Maybe an error of inattention before making the commit but when I remove them it works fine.
