### ISSUE TITLE
KeePassDX as share target

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#280] opened 2019-07-25 17:44 UTC
Please add support for KeePassDX as Android share target. For example if I can't make use of the Android AutoFill feature, i would like to use the share function.

Imagine you are in Firefox mobile and want to have the credentials for the url in the actual tab. Then you can share the url with KeePassDX and KeePassDX search the credentials for the shared url.

**Comment by EnerGeh** [comment] 2019-08-03 10:13
This is a killer feature of Keepass2Android and should definetely be added to KeePassDX! Resolving the URL and preselecting the correct entry ist pretty useful and very smart.

**Comment by ArsTapatun** [comment] 2019-10-30 08:36
This fork is wonderful, but the absence of an effective browser-based workflow compared to keepass2android is truly a tragedy. Very much looking forward to this feature

**Comment by pyro-dev** [comment] 2019-12-13 05:57
Personally, rather than Autofill I would indeed prefer the Keepass2Android behavior, which just sets the matching entry in the Magikeyboard.
I switched from Keepass2Android  early this week, and that's the only point that I could consider a regression. Other than that, the app is pretty great !

**Comment by auanasgheps** [comment] 2020-05-11 22:12
There's no vote button, so I'm writing to endorse this PR! 

Coming from Keepass2Android is the major feature I am missing since most browsers don't yet support native Autofill.

**Comment by J-Jamet** [comment] 2020-05-12 06:56
A code part is already ready because it will use the same external search methods as the autofill in selection mode.
So there is still the code to share the url to create.
If the search is unsuccessful, we must leave the choice to create an entry or select an existing one with a setting. (Linked to https://github.com/Kunzisoft/KeePassDX/issues/435)

**Comment by auanasgheps** [comment] 2020-05-12 14:56
Great to hear! 
But at least for me creating an entry from autofill has way less priority than finding an existing one with the share button, since all browsers (except Firefox) do not support native Autofill.

**Comment by J-Jamet** [comment] 2020-05-21 13:01
I made a first commit which allows using the share with the Magikeyboard ([feature/ShareTarget branch](https://github.com/Kunzisoft/KeePassDX/tree/feature/ShareTarget)).

-  If an entry is retrieved by Web Domain, no worries, the keyboard is filled.

- If several entries are retrieved by Web Domain, I leave the possibility to select among the filtered entries.

Next step -> Activate a setting to automatically fill the keyboard with a share else just do a search

**Comment by J-Jamet** [comment] 2020-06-05 13:24
The functionality is added in version 2.6, it is possible to make an automatic search for the Magikeyboard by activating the corresponding setting.

**Closed by J-Jamet** 2020-06-05 13:24 UTC
Labels: completed developments, feature
