### ISSUE TITLE
Close KeePassDX when locking database

### ISSUE THREAD

**Issue by victorjagu** [Kunzisoft/KeePassDX#1552] opened 2023-04-05 12:50 UTC
**Is your feature request related to a problem? Please describe.**
No problems at all. I just switched from K2A looking for a faster behavior and I found this app. Plus, it comes with a lovely GUI. Thanks for developing this app and leave it open source and free!
I actually have two requests but for a better organization, I will post them separately. I hope this is the better approach :)

**Describe the solution you'd like**
KeePassDX should close itself when clicking the button "lock DB".
Extra: if the app is also removed from the recent app list by doing this, then starting the app should trigger the auto-open DB and prompt for fingerprint perfectly :)

**Describe alternatives you've considered**
1. An option in the settings to always close the app whenever the DB is locked.
2. Long press the "lock" button to "lock and close".

**Additional context**
As I open the DB using the "share" function when I reach a webpage that ask me for credentials (which is pretty straightforward: share the url to KP, fingerprint and done), I have to then lock the DB, cancel the fingerprint prompt and press back several times to close the app, so I can continue working in my stuff.
This might be a minor "thing", but it's turning me crazy hahaha xD

**Comment by J-Jamet** [comment] 2023-04-06 06:25
>  KeePassDX should close itself when clicking the button "lock DB".

This is already the case, but the notion of "closing" an Android application does not have the same meaning as closing a desktop application. Here it is considered closed when there is no more notification indicating an open database, otherwise it is only fixed activity screens.

> Extra: if the app is also removed from the recent app list by doing this, then starting the app should trigger the auto-open DB and prompt for fingerprint perfectly :)

The behavior of the fingerprint auto prompt needs to be improved but this is already covered in a specific issue.

> As I open the DB using the "share" function when I reach a webpage that ask me for credentials (which is pretty straightforward: share the url to KP, fingerprint and done), I have to then lock the DB, cancel the fingerprint prompt and press back several times to close the app, so I can continue working in my stuff.

In this case, the problem is more related to the Magikeyboard workflow. I'll have a look but if you lock the database, you normally don't get the biometric prompt, that's what I find strange here.

**Closed** 2023-06-27 18:18 UTC
Labels: feature
