### ISSUE TITLE
Prompted to open database every time I logon

### ISSUE THREAD

**Issue by nollinvoyd** [Kunzisoft/KeePassDX#1625] opened 2023-09-04 17:08 UTC
Samsung Galaxy Tab s5e

I'm guessing this a simple settings issue, but nothing I try is working.  I imported the settings from my phone app which works properly with biometrics, but didn't help 

![dx 1](https://github.com/Kunzisoft/KeePassDX/assets/20844322/22518306-b4ec-484f-886f-b86835368230)

![dx 2](https://github.com/Kunzisoft/KeePassDX/assets/20844322/22f5ac2b-bd1e-4050-af2a-5eb5595eaa9a)

![dx 3](https://github.com/Kunzisoft/KeePassDX/assets/20844322/97e1b580-085b-4e89-b2d2-cbcb12616c6c)

I am forced to go here and select "NewDatabase.kdbx before any credentials are accepted

![dx 4](https://github.com/Kunzisoft/KeePassDX/assets/20844322/96f00ca5-914f-41a6-ac65-7f848520d939)

 - Version: 2.5.4

 - Language: Engkish

Android 11

**Comment by J-Jamet** [comment] 2023-09-04 19:12
The problem here is that the database file cannot be read directly from the password page. This must be due to the time taken by the file manager to check the URI. When you return to the previous screen, your file manager has verified the URI.
The thing is, I can't reproduce the problem, is it a file you're synchronizing somehow? You haven't filled in the bug form.

**Comment by nollinvoyd** [comment] 2023-09-04 22:32
> The thing is, I can't reproduce the problem, is it a file you're synchronizing somehow? You haven't filled in the bug form.

I didn't want to file a bug if it was something settings related.  I'm not sure what you mean by "is it a file you're synchronizing somehow"?

Would it possibly help if I uninstalled/reinstalled? Does importing the settings from my phone app essentially make it identical, because like I said, no problem with my phone install

**Comment by nollinvoyd** [comment] 2023-09-04 23:47
Does this mean something?  I just launched KeePassDX, and it wouldn't progress beyond this point

![20230904_163600](https://github.com/Kunzisoft/KeePassDX/assets/20844322/6c08b788-dc89-4c3c-b6ca-1927e056afb3)

Had to close and relaunch.

**Comment by J-Jamet** [comment] 2023-09-05 17:29
> I didn't want to file a bug if it was something settings related. I'm not sure what you mean by "is it a file you're synchronizing somehow"?

Is it a local file that is not updated externally or do you replace the file on its location? Can you also indicate the content of the URI (content://...) to identify the file manager?

> Would it possibly help if I uninstalled/reinstalled? Does importing the settings from my phone app essentially make it identical, because like I said, no problem with my phone install

No it has nothing to do

> Does this mean something? I just launched KeePassDX, and it wouldn't progress beyond this point

This means that the number of revolutions of the KDF is too high and that you should reduce it if you want it to go faster.

**Comment by nollinvoyd** [comment] 2023-09-05 18:43
> > Is it a local file that is not updated externally or do you replace the file on its location? Can you also indicate the content of the URI (content://...) to identify the file manager?
> 
If your referring to the location of NewDatabase.kdbx, it's in my locaL Keepass  Onedrive sync folder.  As you know, I can either manually select NewDatabase.kdbx within the KeepassDX interface, or choose "Open existing database", after which my biometrics log me in

> > Would it possibly help if I uninstalled/reinstalled? Does importing the settings from my phone app essentially make it identical, because like I said, no problem with my phone install
> 
> No it has nothing to do
> 
I just thought It might undo something I did wrong

>
> > This means that the number of revolutions of the KDF is too high and that you should reduce it if you want it to go faster.
>
If you're saying it would have eventually loaded the database, that situation behaved like a crash.  After several minutes, I had to manually close the app.

KDF? Is this something password related??  How do I adjust the KDF?

**Comment by J-Jamet** [comment] 2023-09-08 17:07
It's simply that the OneDrive application doesn't manage its content-provider correctly : https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync#file-manager-application

If you've set up your database on a more powerful PC, it's normal for your phone to take much longer to decrypt it. https://keepass.info/help/base/security.html

**Comment by nollinvoyd** [comment] 2023-09-09 16:10
I took car of it, but it took a little trial and error.  I uninstalled it, hoping I could start from scratch.  But a strange happened.  When I tried to set it up, selecting the saved database, somehow I got an older version which didn't have the latest changes made on my desktop.   I tried several times with the same result.  

It then occurred to me "What if KeePassDX had retained and was defaulting to that old database information even tho it was uninstalled, and somehow, even tho I was choosing the latest NewDatabase.kdbx.

I still don't know exactly why that would occur, but I deleted all the saved databases within the app, then imported the latest NewDatabase.kdbx, and also the settings from my phone install, and that did it.  Now, biometrics work properly.  All good now.

**Comment by J-Jamet** [comment] 2023-09-09 19:42
KeePassDX doesn't retain any information or database file when the database is closed, it's Google Drive's cache that's at fault, it's also written in the wiki. All you need to do is clear the Google Drive application cache.

**Comment by nollinvoyd** [comment] 2023-09-09 20:23
> KeePassDX doesn't retain any information or database file when the database is closed, it's Google Drive's cache that's at fault, it's also written in the wiki. All you need to do is clear the Google Drive application cache.

I'll follow that practice in the future.  So, how did i mange to fix it?  Was it the removal of the saved internal database?

**Comment by J-Jamet** [comment] 2023-09-09 20:29
> So, how did i mange to fix it? Was it the removal of the saved internal database?

That's bad Google Drive behavior, so to fix it you'll have to ask Google to make a patch. Otherwise, since the code isn't accessible, you'll have to get yourself hired on this team and fix the problem. Good luck. :D

**Comment by nollinvoyd** [comment] 2023-09-12 16:51
Everything's working very well.  I'm enjoying the ease of operation and the seamless way It has simplified my workflow.  Great!

Please, one more question.  Is there no way to edit an entry within KepassDX? Only on the desktop? Updates can only go one way?

**Comment by joshcangit** [comment] 2023-09-24 11:16
This has always been an issue for me.
A bit difficult to show the message since it goes away when I try to screenshot it.

**Comment by J-Jamet** [comment] 2023-09-30 07:44
> Please, one more question. Is there no way to edit an entry within KepassDX? Only on the desktop? Updates can only go one way? I can't find any info on this.

Try the pen button on the password screen.

>   A bit difficult to show the message since it goes away when I try to screenshot it.

You can take videos in screenshot mode

**Comment by J-Jamet** [comment] 2023-11-04 17:55
I am closing this issue as the problem is indeed with the OneDrive application.

**Closed by J-Jamet** 2023-11-04 17:55 UTC
Labels: bug

**Comment by joshcangit** [comment] 2023-11-05 10:08
I wasn't using OneDrive or Google Drive.
I used the file manager.

**Comment by J-Jamet** [comment] 2023-11-06 07:29
@joshcangit In this case, it's not the same problem as the author's. Open a new way out by being precise.
