### ISSUE TITLE
Crash on start or in random time

### ISSUE THREAD

**Issue by SrgkS** [Kunzisoft/KeePassDX#1182] opened 2021-12-22 09:30 UTC
**Describe the bug**
crash and close randomly and often (from version 3.0.3!)

**To Reproduce**
just start app

**KeePassDX :**
 - Version: from 3.0.3 - 3.0.4
 - Build: free
 - Language: ru

**Android:**
 - Device: xiomi mi5
 - Version: 8
...show me bug report:
`kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at com.kunzisoft.keepass.app.database.IOActionTask$execute$1$1$asyncResult$1.invokeSuspend(IOActionTask.kt)@a393590]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.StackOverflowError: stack size 1037KB
	at kotlinx.coroutines.android.HandlerContext.toString(HandlerDispatcher.kt:152)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.internal.DispatchedContinuation.toString(DispatchedContinuation.kt:251)
	at kotlinx.coroutines.DebugStringsKt.toDebugString(DebugStrings.kt:16)
	at  kotlinx.coroutines.CompletedContinuation.toString(Unknown Source:22)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.CancellableContinuationImpl.toString(CancellableContinuationImpl.kt:506)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.toString(JobSupport.kt:1414)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:320)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more
`

**Comment by J-Jamet** [comment] 2021-12-22 10:24
I had a Google Play user report on this problem but was never able to reproduce it.
I have several theories: 

- Either it's from Kotlin, there is a closely related issue but the version is higher so it should be solved.  https://github.com/Kotlin/kotlinx.coroutines/issues/2371
- Or it's a problem with a bad translation.
- Or it's a problem with a specific type of device / android version

But the main problem is that I can't reproduce it, so I updated the Kotlin libraries and plugins for the next build but I don't even know if that will really solve the issue.

**Comment by J-Jamet** [comment] 2021-12-22 13:14
Maybe the bug is related to https://github.com/Kunzisoft/KeePassDX/issues/509#issuecomment-999565467 because the definition of a complex XML drawable does not work on Android 8 and loops the internal image parser.

**Comment by J-Jamet** [comment] 2021-12-22 13:16
I also removed the request for write permissions, which is normally unnecessary with SAF. I will create a test version and upload it here and you will tell me if the crashes happen again.

**Comment by J-Jamet** [comment] 2021-12-22 13:26
[KeePassDX_test_202122171417.zip](https://github.com/Kunzisoft/KeePassDX/files/7762838/KeePassDX_test_202122171417.zip)
Can you tell me if it works with this test build?

**Comment by SrgkS** [comment] 2021-12-23 06:15
The databases are not opened (probably due to unavailability of write-permission).
Crashes continue randomly, trace log:
`kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at com.kunzisoft.keepass.app.database.IOActionTask$execute$1$1$asyncResult$1.invokeSuspend(IOActionTask.kt)@a95cc89]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.StackOverflowError: stack size 1037KB
	at kotlinx.coroutines.MainCoroutineDispatcher.toStringInternalImpl(MainCoroutineDispatcher.kt:61)
	at kotlinx.coroutines.android.HandlerContext.toString(HandlerDispatcher.kt:152)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.internal.DispatchedContinuation.toString(DispatchedContinuation.kt:251)
	at kotlinx.coroutines.DebugStringsKt.toDebugString(DebugStrings.kt:16)
	at kotlinx.coroutines.CancellableContinuationImpl.toString(CancellableContinuationImpl.kt:506)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.toString(JobSupport.kt:1414)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.DisposeOnCancel.toString(CancellableContinuation.kt:385)
	
....at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:320)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more`

**Comment by SrgkS** [comment] 2021-12-23 06:21
Version 3.0.2 works fine, what changed in 3.0.3 (3.0.4)?

**Comment by J-Jamet** [comment] 2021-12-27 08:31
`git diff 3.0.2 3.0.3`

**Comment by J-Jamet** [comment] 2022-01-04 11:34
> The databases are not opened (probably due to unavailability of write-permission).

Permissions don't normally change anything, so the fact that there are no permission shouldn't prevent opening.

**Comment by J-Jamet** [comment] 2022-01-18 11:54
Can you tell me if it's fixed with version 3.1? https://github.com/Kunzisoft/KeePassDX/releases/tag/3.1.0

**Comment by J-Jamet** [comment] 2022-01-21 12:11
I have no more crash feedback in the console play store so I guess it's resolved for you.

**Closed by J-Jamet** 2022-01-21 12:11 UTC
Labels: bug
