### ISSUE TITLE
com.android.providers.downloads has no access / Saved shortcut path

### ISSUE THREAD

**Issue by descendingnerdliness** [Kunzisoft/KeePassDX#1591] opened 2023-07-14 16:28 UTC
**Describe the bug**
When I try to open the .kdbx I get this notice:
"com.android.providers.downloads has no access"
I believe this is probably a security feature of Android 12 and need to know how to get around it.

**To Reproduce**

1. open keepassdx
2. select db file
3. enter password

**Expected behavior**
DB opens

**KeePass Database**

 - Originally Created with:  KeePass of some ancient version and upgraded at some point. Copied from Kubuntu desktop over KDEConnect where it is used with KeePassXC 2.7.5.

 - File provider: I do not know.
 - Size: 566.2KB
 - Contains attachment: Not that I recall.

**KeePassDX:**

 - Version: 3.5.1

 - Language: English
 - Android 12
 - Device: Galaxy S21
 - Version: 5G

**Additional context**

**Comment by jivarson** [comment] 2023-08-09 10:48
I can always open a database from local storage, but once I need to open it a again (being remembered), it shows up as another name and I'm being denied access.

I have to go back and click on the database from the main screen
![Screenshot_20230809-124309](https://github.com/Kunzisoft/KeePassDX/assets/25992469/33156d88-099b-4944-ae53-524d6377c10f)

**Comment by J-Jamet** [comment] 2023-09-09 20:20
Can you indicate the content provider used by the URI: content://...

**Comment by phantom2983** [comment] 2023-11-05 06:44
I have the same mistake. Do you need this link, which is shown in the screenshot?

**Comment by phantom2983** [comment] 2023-11-05 07:17
I have the same mistake. Do you need this link, which is shown in the screenshot?
![Screenshot_2023-11-05-10-22-58-103_com kunzisoft keepass free](https://github.com/Kunzisoft/KeePassDX/assets/149926727/9e0e4a6b-932c-4279-bfa9-d9d9cc0beff5)

**Comment by J-Jamet** [comment] 2023-11-06 07:35
The last screenshot shows that you have access to open the database. So it's very strange. 
The message appears if the result of the canRead and canWright commands returns false for your file manager.
It's only a short step from there to saying that Samsung's overlay adds bugs to the basic file manager.

**Comment by J-Jamet** [comment] 2023-11-06 07:35
Are you on a custom ROM?

**Comment by phantom2983** [comment] 2023-11-06 07:41
MIUI 12.1.4.0, Android 11, Xiaomi Mi9T, KeepassDX 4.0.2

**Comment by J-Jamet** [comment] 2023-11-06 07:48
You are not on the same configuration as the author of the issue.
Is the file stored locally on the device and not used by another application at the same time?

**Comment by phantom2983** [comment] 2023-11-06 08:21
The database file is stored locally on the device in the Downkoad/KeepassXC folder and is not used by other applications. The specified problem is reproduced quite simply - we block the database, unload the application from memory, open it again and see the message that access to the file has been canceled by the file manager.

https://github.com/Kunzisoft/KeePassDX/assets/149926727/e82b0c1f-6d3e-4afc-9605-9cc02e25f4de

**Comment by J-Jamet** [comment] 2023-11-06 08:49
I see you're using a key file, the same principle is used for this file too. Is it also local and not used by another application?

**Comment by phantom2983** [comment] 2023-11-06 08:52
yes, the key file is also stored locally in the phone's memory

**Comment by J-Jamet** [comment] 2023-11-06 08:54
Can you create a new database stored in the same location but without a key file? This will invalidate or validate this bug track.

**Comment by phantom2983** [comment] 2023-11-06 09:10
I used the same database, just disabled the use of the key file in it - the result is the same

**Comment by J-Jamet** [comment] 2023-11-06 09:21
Have you tried opening your database with https://github.com/zhanghai/MaterialFiles and seeing if the problem persists?

**Comment by J-Jamet** [comment] 2023-11-06 09:32
I watched your video again and it looks like you're accessing the application from a weird shortcut (maybe autogenerated with a path or something).
Normally, you can't access the password screen directly without entering the path or putting the star on the database you want to open directly.
I think you're trying to open the application with a shortcut on your system that doesn't handle file rights at all. Try reopening the application from its original launcher.

**Comment by phantom2983** [comment] 2023-11-06 09:43
it seems there is progress - your assumption about the shortcut and the star on the base is most likely correct. I put an star on the base and the error is no longer reproduced. But why does this behavior initially take place - is it an error in the program or an error in the MIUI shell?

**Comment by J-Jamet** [comment] 2023-11-06 10:22
There are multiple entry points in the program, so I think your system automatically saved the entry point as a shortcut with a file path even though it wasn't asked. And you use this shortcut without realizing that the saved path is not good.

**Comment by J-Jamet** [comment] 2023-11-06 10:24
I close the issue, I can't do anything from KeePassDX for this.

**Closed by J-Jamet** 2023-11-06 10:24 UTC
Labels: bug, invalid
