### ISSUE TITLE
Could not save database with PCloud

### ISSUE THREAD

**Issue by undecomposed** [Kunzisoft/KeePassDX#788] opened 2020-11-18 13:24 UTC
**Describe the bug**
On Android 10, when opening database from a third-party application using the file picker, any attempt to edit database entries or create database entries results in an **Could not save database** error.

**To Reproduce**
1. Open KeePassDX.
2. Click **Open existing database**
3. In the file picker, click the hamburger menu.
4. Scroll to the bottom of the menu.
5. Click the application to select the file from (pCloud in my instance).
6. Click the KeePass database.
7. Enter the decryption details (just the password in my case).
8. Tap **Open**.
9. Click the plus button at the bottom right corner of the screen.
10. Tap **Add entry**.
11. Set the **Title** field as _test_.
12. Tap the checkmark button at the bottom of the screen to save changes.

**Expected behavior**
The new entry is saved successfully.

** Keepass Database **
 - Created with: Windows KeePass 4.46.
 - Version: 2
 - Location: pCloud.
 - Size: 3.7 MB
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.9.1
 - Build: Free
 - Language: English.

**Android (please complete the following information):**
 - Device: OnePlus 6T
 - Version: 10.3.6

**Additional context**
 - Browser for Autofill: Microsoft Edge.

**Comment by J-Jamet** [comment] 2020-11-18 15:18
The problem comes from the content-provider of the file manager application (here PCloud).
It seems that PCloud does not open the URI for writing but only for reading only when a write request is asked by KeePassDX.
I will test but I don't think I can do better, you have to ask PCloud to change this behavior.

**Comment by J-Jamet** [comment] 2020-11-18 15:41
I just tested and indeed, the behavior of PCloud is not as expected. So I advise you to download the file from PCloud, modify it from the Download folder and then re-download it in PCloud once the changes have been made. I write the note in the wiki.

**Comment by stingray21** [comment] 2020-12-12 09:30
I understand that it's not because of KeepassDX that this does not work and that file sharing is not in the scope of this project, but it would be great to find a solution. Having European hosted and encrypted file sharing to sync the database would be really nice.

I could try reaching out to pCloud, if you could provide a little more information what the exact problem is.

**Comment by undecomposed** [comment] 2020-12-20 15:01
My understanding was that pCloud was allowing external applications to get a file in read only mode.

**Comment by MisterY** [comment] 2021-01-02 20:05
If simply looking for a solution, there are at least two:
1. Synchronise with rclone,
2. Use KeePass2Android

**Comment by J-Jamet** [comment] 2021-01-02 20:38
3. Contact PCloud to change the behavior of their app
4. Create a file manager that uses their API
5. Download the file from PCloud to modify it and re-upload it when you are done

**Comment by undecomposed** [comment] 2021-01-09 18:15
> If simply looking for a solution, there are at least two:
> 1. Synchronise with rclone,
> 2. Use KeePass2Android

Unfortunately, KeePass2Android has the same issue

**Comment by MisterY** [comment] 2021-01-09 22:02
No, it doesn't. It supports WebDAV and has been working beautifully for years. 
Recently the pCloud support has been fixed, apparently, but I haven't tried it.

**Comment by J-Jamet** [comment] 2021-01-10 11:08
KeePass2Android directly integrates the Pcloud API, which I don't want for several reasons that I mentioned [here](https://github.com/Kunzisoft/KeePassDX/issues/342#issuecomment-533993154) and in the [wiki](https://github.com/Kunzisoft/KeePassDX/wiki/File-Manager-and-Sync). 

If PCloud knowingly blocks requests to open files for writing, it's to use their API. This is a method I deplore and I won't play this game, I want KeePassDX to remain an editor not a code aggregator for external file manager. 
It's horrible maintenance to add each new trendy API, just to find a workaround because the company doesn't implement its content provider correctly.
It would be enough to allocate writing to not have to manage the complete maintenance of an API.

KeePass2Android integrates them, but not KeePassDX for good reasons, we just don't have the same way of seeing things, and that's why I made this app.
Afterwards, people use the tools they obviously want, but I personally wish to keep the philosophy of free software in the creation of the architecture and not be subjected to each new company or fashionable protocol that appears. (maybe my French side) 
KeePass and KeePassXC on PC don't have to embed Cloud APIs in their code, I don't see why derivatives on phones should when there are documented, secure and official solutions provided by Android (storage access framework).

I will maybe do an external file manager with these APIs with plugins but I'd rather devote myself to important issues than finding workarounds for companies that block the functionality of their apps.

**Comment by MisterY** [comment] 2021-01-10 11:14
Just FYI, WebDAV is not a "fashionable protocol". It's been around for 24 years.

**Comment by J-Jamet** [comment] 2021-01-10 11:19
I have nothing against WebDAV, on the contrary, it is a good protocol. But I want to keep the principle of encapsulation., it is a protocol for information transfer that requires internet (and internet permission). KeePassDX is only a file editor and not a file manager, WebDAV must be integrated in a file manager, that's all.

**Comment by J-Jamet** [comment] 2021-01-10 11:34
Everybody wants WebDAV and Cloud integration, which I understand very well, it just takes time to create a correct file manager that manages the protocol with a content provider. It is not a lasting solution to provide a strong link between the two concepts in a single application when it would give much more advantages to separate them and do this in a dedicated app.

**Comment by stingray21** [comment] 2021-03-24 14:35
I contacted pcloud about this issues. I wrote "KeepassDX" in my email and even liked to this issue, so I am not sure if it is a mix-up or typo that they wrote Keepass (with DX) in their reply.
This is what they wrote:
*As far as we know KeePass did not implement their apps to work with our EU data region accounts, since we have that issue since then with their app. We confirm that the issue is not on our end.*

**Comment by J-Jamet** [comment] 2021-03-24 14:52
I don't see the connection with the European region at all... If their PCloud application doesn't work with European accounts it has nothing to do with KeePassDX, they just have to fix their servers. 

It must be a generic support answer that doesn't bother to look at the content provider of their app. But it is in their interest to avoid the question, they want us to integrate their API in our app.
Nice try though. ;)

**Comment by stingray21** [comment] 2021-03-24 17:40
I am not an expert at all on this topic, but I set up Joplin to sync with pCloud via webdav. There you have to use different urls depending on the region, i.e. `https://webdav.pcloud.com` and `https://ewebdav.pcloud.com` (with the additional **e**) for European account. Could something like that be the reason why the region matters?
(If you have an account with pCloud you can choose whether you want to use their US or European server.)

**Comment by J-Jamet** [comment] 2021-03-26 11:09
Joplin must integrate the corresponding API directly into their code, it is indicated on their website. 
If there is a European region account problem it is either a problem of their API (which is not in KeePassDX) or of their PCloud application (which must also contain their API).
It has nothing to do with KeePassDX, here we are only concerned with the content provider of the PCloud application that provides the data streams of the files, no matter how they provide them, it is their concern.

**Comment by stingray21** [comment] 2021-03-30 09:39
I replied to their last response, this is what they said:

`Since KeepassDX is a third party application, it hasn't been tested with pCloud. Sometimes files can not be edited when in the pCloud app so you have to download them locally, edit and upload the new file to pCloud.`

Which is basically point 5) for your list above ;) 

If you have more details already available on what specifically *PCloud needs to change about the behavior of their app* , I am happy to follow up with them. They seem to be pretty responsive.
But if this would take a lot of work and time for you, just forget about it :) I'm already very pleased and grateful for what you did so far.

I can also try helping in other ways to make it work, if you could point me towards where to start :)

**Comment by J-Jamet** [comment] 2021-03-30 10:46
Thank you for your investment, it is appreciated.

> If you have more details already available on what specifically PCloud needs to change about the behavior of their app , I am happy to follow up with them

I don't know what they need to change, the PCloud app is not open source.
And even more important, it's not up to me, a freelancer working on his own time, to give courses to a big company.
There is Google documentation, it's not so hard to find. ;)
https://developer.android.com/guide/topics/providers/create-document-provider

I will look at the subject later when making the new separate file manager application dedicated to KeePassDX.

**Comment by stingray21** [comment] 2021-03-30 18:03
Thank you! 

I will try looking more into it and learning more about it.

Let me know if I can help with anything specifically.

**Comment by J-Jamet** [comment] 2022-02-19 10:32
As this issue is linked to an external API, I close this issue, you can continue to discuss on the FileSync application dedicated to file synchronization. https://github.com/Kunzisoft/FileSync/issues/6

**Closed by J-Jamet** 2022-02-19 10:32 UTC
Labels: bug, out of scope, FileSync

**Comment by gilbsgilbs** [comment] 2022-04-15 07:54
I suspect this issue was fixed in d217b5274411318ffe395e6cd84232a80455f7d0. You may want to try with KeePassDX 3.4.0+ to see if it works.
