### ISSUE TITLE
Adding OTP to an entry that has OTP crashes the app

### ISSUE THREAD

**Issue by kurwa-69420** [Kunzisoft/KeePassDX#863] opened 2021-01-18 08:48 UTC
**Describe the bug**
This bug occurred when I accidentally tried to add OTP to an entry that already had OTP.

**To Reproduce**
Requires entry with OTP (format must be STEAM)
Click on entry that has OTP
Click 'Edit'
Click 'Add OTP'

**Expected behavior**
Warn users about the action they're trying to do.

**KeePass Database**
 - Created with: KeePassXC
 - Version: 2.6
 - Location: SD Card
 - Size: 966 KB
 - Contains attachment: Yes

**KeePassDX (please complete the following information):**
 - Version: 2.9.11
 - Build: Free (Play Store)
 - Language: Polish

**Android (please complete the following information):**
 - Device: Lenovo A6 Note
 - Version: 9

**Comment by J-Jamet** [comment] 2021-01-18 09:16
Sorry but I can't reproduce the bug and I have no user reports of crashes in Play Store with this version.
Can you tell me which OTP format is already saved in your entry?

**Comment by kurwa-69420** [comment] 2021-01-18 09:19
I forgot to add that the OTP type was STEAM

**Comment by J-Jamet** [comment] 2021-01-18 09:34
Thank you. Indeed, there is a bug at this level, it will be fixed in the next version.

**Comment by J-Jamet** [comment] 2021-01-21 11:48
I leave the issue open until the branch is merged and tagged on master.

**Closed** 2021-01-25 05:20 UTC
Labels: bug, completed developments
