### ISSUE TITLE
Add custom icone entry like in Keepass for Windows

### ISSUE THREAD

**Issue by sphaira-dev** [Kunzisoft/KeePassDX#471] opened 2020-02-22 08:36 UTC
Could you add the possibility of adding an icon from imported png file to an entry.  For inspiration see the Keepass program for Windows available at the following address:

https://keepass.info

Thanks

**Comment by J-Jamet** [comment] 2020-02-22 09:18
Duplicate of #96 
I close this issue

**Closed by J-Jamet** 2020-02-22 09:18 UTC
Labels: duplicate, feature
