### ISSUE TITLE
needing re-authentication after opened

### ISSUE THREAD

**Issue by BillingCode** [Kunzisoft/KeePassDX#1147] opened 2021-10-29 01:15 UTC
**Describe the bug**
 keepassDX needing re-authentication after opened

authentication prompt shows when using using magi keyboard entry selection although database was opened before using magi keyboard entry selection.

**To Reproduce**
1 open database with advanced unlock
2 while database open begin to reset password by clicking change keyboard icon and selecting magi
3 press key icon for selecting password
4 authentication prompt shows although database was opened before and during these steps
 a. the advanced unlock appears to still hold authentication while "Tap to delete advanced unlocking keys" shows in Android notifications pull-down bar.

**Expected behavior**
I expected the database to mainstay open while using magi keyboard.

**KeePass Database**
 - Created with: Android KeePassDX Version 3.0.2
 - Version: default
 - Location: local FS
 - Size: small
 - Contains attachment: no

**KeePassDX (please complete the following information):**
 - Version: Android KeePassDX Version 3.0.2
 - Build: Playstore Free
 - Language: En

**Android (please complete the following information):**
 - Device: Tella
 - Version: Android 10

**Additional context**
 - Browser for Autofill: [e.g. Chrome version X]

**Comment by J-Jamet** [comment] 2021-10-31 12:03
I close the issue until the problem encountered is more clearly explained because I have not been able to reproduce any bug close to it.

**Closed by J-Jamet** 2021-10-31 12:03 UTC
Labels: bug, invalid
