### ISSUE TITLE
When editing a database entry, the application automatically returns to the unlock interface

### ISSUE THREAD

**Issue by Vstory** [Kunzisoft/KeePassDX#951] opened 2021-04-04 11:57 UTC
**Describe the bug**
When editing a database entry, it automatically returns to the database unlocking interface.

The problem does not appear every time.

**To Reproduce**
1. Unlock the database, search for any content, click any search result, and enter the entry preview interface.
2. Edit the content of the entry, such as changing the password and changing the remarks.
3. For example, in the pop-up window for generating a password, after clicking Generate Password and clicking Accept the password, the problem may occur.
4. This problem does not occur every time, and I cannot confirm the cause of the trigger.

**KeePass Database**
 - Created with: Windows KeePass 2.47 (64 Bit)
 - Version: KeePass 2-KDBX4.0
 - Location: Local Disk
 - Size: 6.66M
 - Contains attachment: Yes

**KeePassDX:**
 - Version: 2.9.15
 - Version code: 68
 - Build: free
 - Language: Chinese

**Android:**
 - Device: XiaoMi Note 3
 - Version: 9.0

**Additional context**
The database contains many attachments and custom icons.
#936

**Comment by J-Jamet** [comment] 2021-04-04 17:28
Same as #948

**Comment by J-Jamet** [comment] 2021-04-05 18:24
Can you tell me if the issue is well resolved with the last beta (2.9.16 code 69)? Thank you

**Comment by Vstory** [comment] 2021-04-05 22:27
> Can you tell me if the issue is well resolved with the last beta (2.9.16 code 69)? Thank you

I am testing.

**Comment by Vstory** [comment] 2021-04-06 02:01
> Can you tell me if the issue is well resolved with the last beta (2.9.16 code 69)? Thank you

Theme selection: Classic.
Select the entry that contains the two-step verifier code, wait for the entry time to expire, and the application will automatically return to the unlock interface.

**Comment by J-Jamet** [comment] 2021-04-06 06:09
You have simply activated the corresponding setting: Settings - Form filling - (Clipboard) Clear at closing

**Comment by Vstory** [comment] 2021-04-06 06:24
> You have simply activated the corresponding setting: Settings - Form filling - (Clipboard) Clear at closing

？
What I mean is that after running KeePassDX, an entry is selected and nothing is copied.
The application did not reach the time to lock the database, it returned to the unlock interface by itself.

**Comment by J-Jamet** [comment] 2021-04-06 06:27
Ho OK, I don't know why this is happening. I solved the theoretical crashes I got from the Play Store logs and that's all I can do for now because I can't reproduce this issue.

**Comment by J-Jamet** [comment] 2021-04-06 06:53
If someone can upload a database with the problem it would be appreciated

**Comment by Vstory** [comment] 2021-04-06 06:59
> If someone can upload a database with the problem it would be appreciated

This issue is related to the database?
I am tested later.

**Comment by J-Jamet** [comment] 2021-04-06 07:02
The only thing I know is that it is caused by a BadParcelable exception.

**Comment by J-Jamet** [comment] 2021-04-06 15:38
I solved the problem, it was the parcelable of the id of binaries in KDB databases but I don't know why you have the problem for a KDBX database. I'm making 2.9.16 code 70

**Comment by Vstory** [comment] 2021-04-07 01:15
>  but I don't know why you have the problem for a KDBX database. 

😅

**Closed** 2021-04-07 07:58 UTC
Labels: bug, completed developments
